### ISSUE TITLE
[QUESTION] (De)Interleaving the data

### ISSUE THREAD

**Issue by DoDoENT** [jfalcou/eve#1020]
Hi!

I'm trying to use [this example](https://github.com/jfalcou/eve/blob/develop/examples/start_here.cpp) as a basis for my experiments with EVE.

I've conjured up a small example that transforms BGRA pixels to RGB:

```c++
struct BGRAPixel{ std::uint8_t values[ 4 ]; using is_product_type = void; };
struct RGBPixel { std::uint8_t values[ 3 ]; using is_product_type = void; };


// provide support for structured binding
template<>
struct std::tuple_size< BGRAPixel > : std::integral_constant< std::size_t, 4 > {};

template<>
struct std::tuple_size< RGBPixel > : std::integral_constant< std::size_t, 3 > {};

template< std::size_t I >
struct std::tuple_element< I, BGRAPixel > { using type = std::uint8_t; };

template< std::size_t I >
struct std::tuple_element< I, RGBPixel > { using type = std::uint8_t; };

template< std::size_t Index > [[ nodiscard ]] constexpr auto get( BGRAPixel const p ) noexcept { return p.values[ Index ]; }
template< std::size_t Index > [[ nodiscard ]] constexpr auto get( RGBPixel  const p ) noexcept { return p.values[ Index ]; }

bool operator==( BGRAPixel const a, BGRAPixel const b ) noexcept
{
    return a.values[ 0 ] == b.values[ 0 ] && a.values[ 1 ] == b.values[ 1] && a.values[ 2 ] == b.values[ 2 ] && a.values[ 3 ] == b.values[ 3 ];
}

bool operator==( RGBPixel const a, RGBPixel const b ) noexcept
{
    return a.values[ 0 ] == b.values[ 0 ] && a.values[ 1 ] == b.values[ 1] && a.values[ 2 ] == b.values[ 2 ];
}

TEST( EveTest, bgra2rgbAligned )
{

    eve::algo::soa_vector< BGRAPixel > bgra
    {
        BGRAPixel{ 0, 0, 255, 255 },
        BGRAPixel{ 1, 255, 0, 255 },
        BGRAPixel{ 2, 255, 0, 255 },
        BGRAPixel{ 3,   0, 0, 255 },
        BGRAPixel{ 4,   0, 0, 255 },
        BGRAPixel{ 5,   0, 0, 255 },
        BGRAPixel{ 6,   0, 0, 255 },
        BGRAPixel{ 7,   0, 0, 255 },
        BGRAPixel{ 8,   0, 0, 255 },
        BGRAPixel{ 9,   0, 0, 255 },
        BGRAPixel{ 10,  0, 0, 255 },
        BGRAPixel{ 11,  0, 0, 255 },
        BGRAPixel{ 12,  0, 0, 255 },
        BGRAPixel{ 13,  0, 0, 255 },
        BGRAPixel{ 14,  0, 0, 255 },
        BGRAPixel{ 15,  0, 0, 255 },
    };

    eve::algo::soa_vector< RGBPixel > expectedRgb
    {
        RGBPixel{ 255, 0, 0 },
        RGBPixel{ 0, 255, 1 },
        RGBPixel{ 0, 255, 2 },
        RGBPixel{ 0, 0,   3 },
        RGBPixel{ 0, 0,   4 },
        RGBPixel{ 0, 0,   5 },
        RGBPixel{ 0, 0,   6 },
        RGBPixel{ 0, 0,   7 },
        RGBPixel{ 0, 0,   8 },
        RGBPixel{ 0, 0,   9 },
        RGBPixel{ 0, 0,  10 },
        RGBPixel{ 0, 0,  11 },
        RGBPixel{ 0, 0,  12 },
        RGBPixel{ 0, 0,  13 },
        RGBPixel{ 0, 0,  14 },
        RGBPixel{ 0, 0,  15 },
    };

    eve::algo::soa_vector< RGBPixel > actualRgb;
    actualRgb.resize( expectedRgb.size() );

    auto convertBgraToRgb
    {
        []( eve::like< BGRAPixel > auto bgraPixel )
        {
            auto [ b, g, r, a ] = bgraPixel;
            std::cout << "Blue values: " << b << std::endl; // Why is this printed twice?!?
            eve::wide< RGBPixel > rgbPixel{ r, g, b };
            return rgbPixel;
        }
    };

    eve::algo::transform_to( bgra, actualRgb, convertBgraToRgb );

    for( auto i{ 0U }; i < actualRgb.size(); ++i )
    {
        EXPECT_EQ( actualRgb.get( i ), expectedRgb.get( i ) );
    }
}
```

This works as expected, but only when I put my pixels in `eve::algo::soa_vector`. The example states that if I use `eve::algo::transform_to[ eve::algo::no_aligning ]` it should be possible to use `std::vector`. However, the example shows the case (polar to cartesian conversion) where each component is in its own vector. The `eve::algo::soa_vector` does the same internally - it uses Structure of Array instead of Array of Structure.

I'm aware that this is the more efficient way of storing data for SIMD processing, but in my case, I don't control the data. The images that I need to process come in interleaved BGRA format, so I need EVE to actually de-interleave the data during load into SIMD register and interleave it back when writing to memory. How to do that?

I know that some CPUs have builtin instructions for deinterleaving load and interleaving store (e.g. ARM has `vld4q_u8` intrinsic that loads 4 NEON registers with deinterleaved data and `vst3q_u8` for storing 3 SIMD registers interleaved; Intel needs to emulate that with load+shuffle (or shuffle+store)).

Does EVE support that? Is there a tag, such as `eve::algo::no_aligning` to tell EVE that the data needs to be loaded and/or stored with (de)interleaving? I couldn't find any example for that?

If there is no support, do you plan to add it?

Also, if you check the source above, you'll see that the "Blue values:" is printed twice, meaning that this lambda is called twice. Why is that? I'm currently testing on Intel with SSE4 and WASM SIMD (using hacks from #982).

**Comment by jfalcou** [comment]
Deinterleaving data is the work for shuffle, which is still under development (#334).
We have plan for soa_view so maybe it's a job for that somehow;

Loading as deinterleaved using the load from ARM is something that could be mapped. 
But it is not a generic system so it'll also need to be done for size > 4.

**Comment by DenisYaroshevskiy** [comment]
We don't have a deinterlieave data out of the box.

Not that it's not doable, just we don't have it.

Do you want the output to be one vector, just skipping every 3 out of 4 elements?
I think I can pull it off but not with our algorithms.

Is this is what you need:

```
void transfrom_BGRA_to_RGB(std::vector<std::uint8_t> const& bgra, std::vector<std::uint8_t> auto& rgb):
```

Or are you ok with the output being in parallel vectors?

**Comment by DenisYaroshevskiy** [comment]
More testing showed that I also messed up the ending.

Just because I could've loaded the whole register, does not mean I can store the whole register.

**Comment by DenisYaroshevskiy** [comment]
I will fix the bugs in the pr, probably this evening.

**Comment by DenisYaroshevskiy** [comment]
Done.

https://github.com/jfalcou/eve/blob/bc9ee937327e84fbcda4ef3a1b6d879420477c78/examples/algorithms/writing_new/bgra_rgb__using_eve_to_shuffle_bytes.cpp#L10
