### ISSUE TITLE
Adding git tags, and github releases

### ISSUE THREAD

**Issue by the-moisrex** [jfalcou/eve#1023]
Since I'm (at least trying to) use [CPM.cmake](https://github.com/cpm-cmake/CPM.cmake) in my project and this great project still doesn't have a tag or a github release, I'm afraid it would require a little bit of getting hacky; I can I ask for releases or a git tag with a name like "v1.20.5"?

Not specifying a version doesn't really sets well with CPM;
```cmake
CPMAddPackage(
        NAME eve
        GITHUB_REPOSITORY jfalcou/eve
)
```
The error if you try:
```
CMake Error at eve-subbuild/eve-populate-prefix/tmp/eve-populate-gitclone.cmake:40 (message):
  Failed to checkout tag: 'v'
```

Thanks

**Comment by jfalcou** [comment]
We can do that. We currently had no release as we're still breaking things.
@DenisYaroshevskiy  should we get a a v0.0.1 or something for this ?

**Comment by DenisYaroshevskiy** [comment]
> We can do that. We currently had no release as we're still breaking things.
> @DenisYaroshevskiy should we get a a v0.0.1 or something for this ?

Up to you - whatever needs to be done for deployment. As long as we can reasonably live at head and break ppl's code on a regular basis )

**Comment by the-moisrex** [comment]
I do have [some benchmarks](https://github.com/the-moisrex/webpp/blob/dev/benchmarks/ieuqals/iequals_benchmark.cpp) on this that I needs to re-check as well which requires me to make my project compile-able again 😂; but overall, not having to deal with alignment and manual for loops is great. I'm looking forward to not having to deal with is_less and if_else functions as well if all possible!

**Comment by the-moisrex** [comment]
It's really great; but it's missing 2 optimization features:

1. checking the size (they're not equal if they don't have the same size)
2. the user can provide the information about whether or not the A or B are all in small caps or all capital letters.

And also the to_lower and to_upper could be their own utilities (which I made them [here](https://github.com/the-moisrex/webpp/blob/dev/core/include/webpp/strings/to_case.hpp), with some [benchmark](https://github.com/the-moisrex/webpp/blob/dev/benchmarks/tolower/tolower_benchmark.cpp)). The same goes for is_lower and is_upper.

And all of these are only about ascii and doesn't work for any other locale actually. So far away from complete.

But this is what some of us need; specially in places like parsing HTTP headers or dealing with protocols that only accept ASCII.

I essentially thinking about making a whole string related algorithms with SIMD. Next level would be writing a parser with SIMD; imagine parsing HTTP protocol with SIMD! That would be the fastest http parser ever created I guess 😄 

You know what? I'm just gonna open a couple of [Github projects](https://github.com/the-moisrex/webpp/projects) for SIMDfying string algorithms and a simd parser; they're too good of dreams!

**Comment by DenisYaroshevskiy** [comment]
> It's really great; but it's missing 2 optimization features:

Well, it will assert that they are the same length and crash you in debug mode :)

> And also the to_lower and to_upper could be their own utilities (which I made them here, with some benchmark). The same goes for is_lower and is_upper.

I like the unsigned trick better tbh.

>  Next level would be writing a parser with SIMD; imagine parsing HTTP protocol with SIMD!

There is https://github.com/simdjson/simdjson - so yeah it's doable. I was thinking doing a CTRE backed, also'd be cool.
But good luck.
I think algorithms will occupy me for the next ever.
Lemme know if you need anything.

**Comment by jfalcou** [comment]
I would like to keep some semantic versionning going on. So whta about v0.0.202110?
The year /month is in and I can tsill use major vzrsion later if api breaks.

**Comment by jfalcou** [comment]
So vYYYY.MAJOR.MINOR

**Comment by the-moisrex** [comment]
Yes that's a nice way; version is not a float number so you don't have to worry about not having room for the next minor version.
