### ISSUE TITLE
[FEATURE] Extract lines from a `eve::wide<eve::struct_support<A,B,...>>` object

### ISSUE THREAD

**Issue by aguinet** [jfalcou/eve#1053]
**Is your feature request related to a problem? Please describe.**

I have a `eve::wide<eve::struct_support<A,B,C>>` object, and I would like to extract the first N lines, so for instance `eve::wide<eve::struct_support<A,B>>`. I guess it could be extended to extract an arbitrary set of lanes, defined by a set of ranges :)

**Describe the solution you'd like**

In my specific case:

```cpp
auto v = eve::wide<eve::struct_support<A,B,C>>(...);
auto fv = eve::first<2>(v);
```

**Describe alternatives you've considered**

Copy values by hand with `get` :)

**Comment by DenisYaroshevskiy** [comment]
This should be a `no-op` and it's a swizzle. I will have a look if we optimise it well already.

**Comment by DenisYaroshevskiy** [comment]
Correct result: https://godbolt.org/z/9xx8frr6v

But codegen is bad: https://godbolt.org/z/cTvhsKxrf

@jfalcou should identity swizzle handle this?
Or should it be a separate swizzle.

**Comment by DenisYaroshevskiy** [comment]
I misunderstood, you want lInes not lAnes

**Comment by DenisYaroshevskiy** [comment]
@jfalcou will have a proper solution soon, workaround: https://godbolt.org/z/eWK9r4x7c

**Comment by aguinet** [comment]
Indeed sorry I want lines, changing the name... Thanks for the prompt answers!
