### ISSUE TITLE
[BUG] Some tutorial examples no longer work

### ISSUE THREAD

**Issue by partouf** [jfalcou/eve#1070]
https://jfalcou.github.io/eve/html/tutorial_if_else.html

Namely the first one (https://godbolt.org/z/YxeMqxz8v) and the very last one (https://godbolt.org/z/MhvvbTE4a).

**Comment by DenisYaroshevskiy** [comment]
Missing brace: https://godbolt.org/z/rY9ooK948
Thanks for reporting

**Comment by jfalcou** [comment]
The second one should be https://godbolt.org/z/7KfdTbn1c
This is an old piece of doc and the code inside is not in the examples/ test set, this should also be revised.
