### ISSUE TITLE
[BUG] sizeof(eve::wide<eve::struct_support<tuple>, C>) should be sizeof(tuple)*C

### ISSUE THREAD

**Issue by aguinet** [jfalcou/eve#1075]
**Describe the bug**
This can be seen with this CE by joel: https://godbolt.org/z/8TMf4aKxn

**To Reproduce**
See CE link above :)

**Expected behavior**
We would expect `sizeof(eve::wide<kumi::tuple<int,int>>)` to be `32`.

**Setup:**
 - Compiler and compiler's version: gcc 11
 - OS: Compiler Explorer OS :)
 - Processor Architecture: N/A
 - Instructions Set used: N/A

**Additional context**

**Comment by DenisYaroshevskiy** [comment]
Sorry, but why?

1) In what context do you need sizeof(wide)?
2) Wide should not rly exist in assembly in any way
3) It can't be sizeof(tuple)*C due to how implementation of smaller cardinals works:
wide<int, 2> hs the same implementation as wide<int, 4>

**Comment by DenisYaroshevskiy** [comment]
The reason I asked is that I have a suspicion that you are trying to store `wide` in a data structure and it's not designed for that.

You are better off storring array<int, eve::expected_cardinal_v<int>>.

You might want to align that.

This will behave like cardinal size and all of that 

Let me know if you need help with it.

**Comment by jfalcou** [comment]
The latest commit seems to have a good effect on some codegen. So the change is worthwhile.
Should we close this?

**Comment by aguinetqb** [comment]
I am indeed doing some nasty UB thing here: https://github.com/aguinet/ecsimd/blob/master/include/ecsimd/mgry_mul.h#L107-L114 . Like said in the comment, I don't know how to make this cleaner (yet).

Moreover, this remove padding, that creates weird codegen things, like in here: https://godbolt.org/z/Keo1MaGh1

As a final note, I think it's a "better" design to have this equivalence in size, especially if you want to store this in another object, in order not to waste memory space.

**Comment by aguinetqb** [comment]
And closing it as joel fixed it :)

**Comment by DenisYaroshevskiy** [comment]
You don't need to do stores: you can just assign from __256i to eve::wide<int, eve::fixed<8>> and back https://godbolt.org/z/YzvM5hvrv
