### ISSUE TITLE
[FEATURE] Create eve/std.h to emulate std::experimental::simd

### ISSUE THREAD

**Issue by hkaiser** [jfalcou/eve#1098]
See https://en.cppreference.com/w/cpp/experimental/simd

**Comment by jfalcou** [comment]
As per discussion, this amounts to providing properly named using clauses to provide a `eve::experimental::simd` version of `std::simd` and `std::simd_mask` .

**Comment by jfalcou** [comment]
@hkaiser Looks like the type generated by `std::experimental::simd/native_simd<T>` are rather inconsistent or even silly.
 - On ARM and PPC, `simd<T>`is just T and `simd_mask<T>` is bool.
 - On AVX, `native_simd<T>` is what is expected but for `simd<T>`, it's m256 for float/double but reverts back to m128i for integral types.
 
 Should we consider that compiler bugs and just don't test those or should we emulate this inconsistent behavior?

**Comment by hkaiser** [comment]
> @hkaiser Looks like the type generated by `std::experimental::simd/native_simd<T>` are rather inconsistent or even silly.
> 
> * On ARM and PPC, `simd<T>`is just T and `simd_mask<T>` is bool.
> * On AVX, `native_simd<T>` is what is expected but for `simd<T>`, it's m256 for float/double but reverts back to m128i for integral types.
> 
> Should we consider that compiler bugs and just don't test those or should we emulate this inconsistent behavior?

I think they simply have not implemented things on ARM and PPC platforms yet. Therefor the fallback to intrinsic types...

**Comment by jfalcou** [comment]
OK so I'll de-activate the test for ARM/PPC and fix AVX with a std::conditional or something

**Comment by hkaiser** [comment]
> OK so I'll de-activate the test for ARM/PPC and fix AVX with a std::conditional or something

I don't think you should try to reproduce problems their implementation exposes. Let's go with what the specification says.

**Comment by jfalcou** [comment]
Changed the test to be that:
https://github.com/jfalcou/eve/blob/6add70d52f66a8a0189afe24ae8753d582b803bd/test/unit/meta/std_compatibility.cpp

Basically, I ignore whatever the current bad QoI of the compiler does and check meaningful sizes.

**Comment by jfalcou** [comment]
Fixed in b94f8a00fa1f2751930708894c743ba8ea0d62b8
