### ISSUE TITLE
[FEATURE] Support vcpkg

### ISSUE THREAD

**Issue by kreuzerkrieg** [jfalcou/eve#1112]
Any chance to get `eve` added to the `vcpkg` repo?

**Comment by jfalcou** [comment]
This is something we can look into. Now, the MSVC support of EVE is still in the work.

**Comment by kreuzerkrieg** [comment]
Not related to MSVC, vcpkg is cross platform, I'm using it on ubuntu with clang. When declaring in the package supported platforms and compilers just skip MSVC.

**Comment by jfalcou** [comment]
Sounds fair, we'll give it a try then.

**Comment by kreuzerkrieg** [comment]
If you think it will take you too much time to get to this task I can take it. It's been a while since I touched the `vcpkg` but I guess I can do it in a couple of hours

**Comment by jfalcou** [comment]
If you have some experience, patches are welcomed! We'll help you if some idiosyncrasies are required.

**Comment by kreuzerkrieg** [comment]
I will submit it directly to vcpkg, then you can grab it and take it from here on

**Comment by jfalcou** [comment]
Great

**Comment by kreuzerkrieg** [comment]
Done
https://github.com/microsoft/vcpkg/pull/22179

**Comment by jfalcou** [comment]
Thanks a lot!
