### ISSUE TITLE
[QUESTION] STL/EVE equivalence

### ISSUE THREAD

**Issue by kreuzerkrieg** [jfalcou/eve#1113]
Just curious. Is there some kind of mapping table, how to map STL stuff to EVE?
Like std::inclusive_scan maps to eve::algo::inclusive_scan_to, ok,  this one is quite obvious. But, for example, what replaces std::accumulate?

**Comment by jfalcou** [comment]
std::accumualte can't be parallelized, contrary to std::reduce. And std::reduce is tied to eve::reduce.
We're working on improving the doc for the algorithm but normally, most of them are transparent if you look at eve/algo/.
You also have a bunch of examples in the examples/ folder on how to use algorithms.

**Comment by DenisYaroshevskiy** [comment]
There is no map.

Here is a list of all algorithms in a very hacky form: https://github.com/jfalcou/eve/blob/379a430274332973429ab61f4590ccf54fb271af/include/eve/algo/README.txt#L7

Here are a bunch of examples:
https://github.com/jfalcou/eve/blob/379a430274332973429ab61f4590ccf54fb271af/examples/start_here.cpp#L16

Feel free to create a more specific question with "I need to do X" and we'll see if we can help you.

**Comment by kreuzerkrieg** [comment]
> std::accumualte can't be parallelized, contrary to std::reduce. And std::reduce is tied to eve::reduce. We're working on improving the doc for the algorithm but normally, most of them are transparent if you look at eve/algo/. You also have a bunch of examples in the examples/ folder on how to use algorithms.

now when you said that, well, right, it was a dumb example :)

**Comment by kreuzerkrieg** [comment]
> Feel free to create a more specific question with "I need to do X" and we'll see if we can help you.

Thanks!
Is "issues" on github is a right place? or you prefer stackoverflow?

**Comment by DenisYaroshevskiy** [comment]
> Is "issues" on github is a right place? or you prefer stackoverflow?

Issues are perfectly alright.
Preferably with specific types and ideally with scalar code as an example of what you want.
If you know the specific architecture that'd also help.

**Comment by kreuzerkrieg** [comment]
Shall we start here?
how would you rewrite this one
```
const auto blocks = (len + (constants::NMAX - 1)) / constants::NMAX;
for (size_t i = 0; i < blocks; ++i) {
	const auto block = i * constants::NMAX;
	for (uint32_t j = 0; j < constants::NMAX && block + j < len; ++j) {
		lower_componnet += buf[block + j];
		upper_component += lower_componnet;
	}
	lower_componnet %= constants::BASE;
	upper_component %= constants::BASE;
}
```
or the same calculation in one loop
```
for (size_t i = 0; i < len; ++i) {
	lower_componnet += buf[i];
	upper_component += lower_componnet;

	if ((i + 1) % constants::NMAX == 0 || i + 1 == len) {
		lower_componnet %= constants::BASE;
		upper_component %= constants::BASE;
	}
}
```
and if it looks like adler32 it is because its adler32 :)
none of the above would autovectorize because of the reduction variable reuse. How would EVE help here to solve this problem?

**Comment by DenisYaroshevskiy** [comment]
Can you add the types here?

I believe that this internal thing:

```
for (uint32_t j = 0; j < constants::NMAX && block + j < len; ++j) {
		lower_componnet += buf[block + j];
		upper_component += lower_componnet;
}
```

is equivalent to:

```
int start = block;
int end = std::min(block + constants::NMAX, len);

int lower_component  = reduce(&buf[start], &buf[end]);
int upper_component = inclusive_scan(&buf[start], &buf[end]);
```

Is that so?

**Comment by kreuzerkrieg** [comment]
no it is more like
```
std::vector<uint32_t> components(constants::NMAX);
size_t buff_pos = 0;
std::span buffer_view(buf, len);
for (auto it = buffer_view.begin(); it != buffer_view.end();) {
	const auto chunk_size = std::min(static_cast<size_t>(constants::NMAX), len - buff_pos);
	auto begin = it;
	std::advance(it, chunk_size);
	auto end = it;

	auto components_end =
			std::inclusive_scan(begin, end, components.begin(), std::plus<uint32_t>{}, lower_component);

	upper_component = std::accumulate(components.begin(), components_end, upper_component);
	upper_component %= constants::BASE;

	lower_component = *(--components_end);
	lower_component %= constants::BASE;

	buff_pos += chunk_size;
}
```
if you rewrite it to STL implementation and do it in two passes.
NMAX is `constexpr uint32_t NMAX = 5552` and it affects the outer loop, and IMHO vectorization is not justified here, but the inner loop, when you are accumulating values, does

As of type, from the example above I think only the `buf` still a mistery, which is `const unsigned char*`

**Comment by DenisYaroshevskiy** [comment]
I am fairly certain that it does not match what you wrote originally.

That version of `inclusive_scan` is called `inclusive_scan_to`.

```
eve::algo::inclusive_scan_to(begin, end, components.begin(), lower_component);
```

Then you add them again, that's eve::algo::reduce

```
eve::algo::reduce(components.begin(), components_end, upper_component);
```

If that passes your unit-tests, you can fuse two loops together and stop writing the components.
I'm trying to put that together.

**Comment by DenisYaroshevskiy** [comment]
I'll be honest, I'm lost a bit in the code at the moment.

This is how you can get all of the `inclusive_scan` values: https://godbolt.org/z/8rPxe4sfe

Please note that in this example the input vector just happens to be aligned, sometimes the first value will be 0.

Let me know if this happens to be sufficient for you to do your thing.

You might also want to have a look at this talk I did last year: https://youtu.be/d6NcnyXjc3I
It uses a bit of an outdated syntax but it explains how the algorithms function.

**Comment by DenisYaroshevskiy** [comment]
I believe you wanted to add the running sums together.
It looks smth like this: https://godbolt.org/z/Kbh91s4b3

**Comment by DenisYaroshevskiy** [comment]
Wait, is this what you want by any chance? https://godbolt.org/z/sMs4GdPxP

**Comment by kreuzerkrieg** [comment]
Thanks Denis! Going to check this code now and try to understand what is written there, looks like I have to explore the documentation since it is more complicated that I initially thought. Thanks again!

**Comment by DenisYaroshevskiy** [comment]
I seriously suggest you watch this talk: https://youtu.be/d6NcnyXjc3I - it will give you an overview of the concepts you need.

**Comment by kreuzerkrieg** [comment]
Watching it right now :)
BTW, your last attempt [here](https://godbolt.org/z/sMs4GdPxP) nailed it

**Comment by DenisYaroshevskiy** [comment]
Great. Please let us know if this works out for you.

Also - if this is a known algorithm, maybe consider adding an example to `eve/examples`?

Here is how it can look like: https://github.com/jfalcou/eve/blob/develop/examples/algorithms/using_existing/case_insensitive_equals.cpp

Pr with hooking up to the test system: https://github.com/jfalcou/eve/pull/1025

Anyways, good luck.

**Comment by kreuzerkrieg** [comment]
Hm... it maybe not a bad idea, let me get my EVE skills polished and we will see.

And, thanks again!

**Comment by jfalcou** [comment]
Cool you solved your issue :)
I'm closing this one issue. Feel free to open new ones if needed.
