### ISSUE TITLE
[BUG] The dependency target "..." of target "..." does not exist.

### ISSUE THREAD

**Issue by the-moisrex** [jfalcou/eve#1126]
**Describe the bug**
Disabling building of tests, benchmarks, and documentations will cause this error while using CPM.cmake:

````
CMake Error at /home/$USER/.cache/CPM/eve/0473c468ff0d44c6aa8d466a61593cbb877720ec/cmake/target/targets.cmake:29 (add_dependencies):
The dependency target "doc.exe" of target "unit.exe" does not exist.
Call Stack (most recent call first):
/home/$USER/.cache/CPM/eve/0473c468ff0d44c6aa8d466a61593cbb877720ec/CMakeLists.txt:41 (include)


CMake Error at /home/$USER/.cache/CPM/eve/0473c468ff0d44c6aa8d466a61593cbb877720ec/cmake/target/targets.cmake:38 (add_dependencies):
The dependency target "unit.api.exe" of target "unit.basic.exe" does not
exist.
Call Stack (most recent call first):
/home/$USER/.cache/CPM/eve/0473c468ff0d44c6aa8d466a61593cbb877720ec/CMakeLists.txt:41 (include)


CMake Error at /home/moisrex/.cache/CPM/eve/0473c468ff0d44c6aa8d466a61593cbb877720ec/cmake/target/targets.cmake:37 (add_dependencies):
The dependency target "unit.arch.exe" of target "unit.basic.exe" does not
exist.
Call Stack (most recent call first):
/home/$USER/.cache/CPM/eve/0473c468ff0d44c6aa8d466a61593cbb877720ec/CMakeLists.txt:41 (include)


CMake Error at /home/$USER/.cache/CPM/eve/0473c468ff0d44c6aa8d466a61593cbb877720ec/cmake/target/targets.cmake:39 (add_dependencies):
The dependency target "unit.meta.exe" of target "unit.basic.exe" does not
exist.
Call Stack (most recent call first):
/home/$USER/.cache/CPM/eve/0473c468ff0d44c6aa8d466a61593cbb877720ec/CMakeLists.txt:41 (include)
````

CPM code:

````cmake
CPMAddPackage(
        NAME eve
        URL https://github.com/jfalcou/eve/archive/refs/tags/v2021.10.0.zip
        VERSION 2021.10.0
        OPTIONS
                "EVE_BUILD_TEST OFF"
                "EVE_BUILD_BENCHMARKS OFF"
                "EVE_BUILD_DOCUMENTATION OFF"
)

````

and it'll get fixed if I just comment the test option:
````cmake
CPMAddPackage(
        NAME eve
        URL https://github.com/jfalcou/eve/archive/refs/tags/v2021.10.0.zip
        VERSION 2021.10.0
        OPTIONS
                # "EVE_BUILD_TEST OFF"
                "EVE_BUILD_BENCHMARKS OFF"
                "EVE_BUILD_DOCUMENTATION OFF"
)

````

But as a user of this library, I don't think I need tests, docs, and benchmarks.

**Comment by DenisYaroshevskiy** [comment]
Auch. As a user, there is nothing to build, everything is header only.
If that helps - the library should be in conan and vcpkg.
Otherwise, @jfalcou will need to pitch in

**Comment by the-moisrex** [comment]
Yeah I'm not going to "just download" and manually setup include directories to use eve.

And the notion of "the library should be in conan and vcpkg" is a deal breaker for me to be honest.

This patch seems to fix the bug though: https://github.com/the-moisrex/eve/commit/80b52663eefee11460abb0aedf4158a5067cf7dc

**Comment by jfalcou** [comment]
What @DenisYaroshevskiy say is that those options just disable tbe targets, but don't impacy installation process. So not passing them in the cpm thing has no impact.

Or does cpm put targets of dependency inside the main project?

**Comment by the-moisrex** [comment]
CPM is just a wrapper around `FetchContent` and `find_package`.

**Comment by the-moisrex** [comment]
Honestly, I don't think even the fix that I gave was a good one.

You can actually see the problem in the [pch.cmake](https://github.com/jfalcou/eve/blob/b94f8a00fa1f2751930708894c743ba8ea0d62b8/cmake/config/pch.cmake#L10) file where we're adding two docs and test executables while there is no way of disabling them with `EVE_BUILD_TEST` and `EVE_BUILD_DOCUMENTATION` variables.

These 3 variables should either be more present in those config files or at least the documentation and test executable configs should be in different files so the user can actually disable them with those flags.

**Comment by jfalcou** [comment]
Some of those inconsistency were fixed in #1124
I'll take a proper look at that tonight.

**Comment by jfalcou** [comment]
@the-moisrex : side question.
Is the code 

```
CPMAddPackage(
        NAME eve
        URL https://github.com/jfalcou/eve/archive/refs/tags/v2021.10.0.zip
        VERSION 2021.10.0
        OPTIONS
                "EVE_BUILD_TEST OFF"
                "EVE_BUILD_BENCHMARKS OFF"
                "EVE_BUILD_DOCUMENTATION OFF"
)
```

The only thing needed to use EVE via CPM ? If yes, OK for you if I put that in the  doc ?

**Comment by the-moisrex** [comment]
> @the-moisrex : side question. Is the code
> 
> ```
> CPMAddPackage(
>         NAME eve
>         URL https://github.com/jfalcou/eve/archive/refs/tags/v2021.10.0.zip
>         VERSION 2021.10.0
>         OPTIONS
>                 "EVE_BUILD_TEST OFF"
>                 "EVE_BUILD_BENCHMARKS OFF"
>                 "EVE_BUILD_DOCUMENTATION OFF"
> )
> ```
> 
> The only thing needed to use EVE via CPM ? If yes, OK for you if I put that in the doc ?

Yes; if the user has [configured CPM](https://github.com/the-moisrex/webpp/blob/dev/cmake/import.cmake) before (which itself is pretty easy), for eve that's the only thing the user has to do.

[Here](https://github.com/the-moisrex/webpp/blob/dev/cmake/packages/eve.cmake)'s my file actually which only includes the above code.

CPM.cmake also has a page that [shows some known libraries](https://github.com/cpm-cmake/CPM.cmake/wiki/More-Snippets) too which this snippet could be on as well.
