### ISSUE TITLE
[QUESTION] how to get register width?

### ISSUE THREAD

**Issue by kreuzerkrieg** [jfalcou/eve#1138]
Is there a way to get a current architecture register width? preferably at compile time? Like, for AVX2 I expect to be able to get `256`

And another question, if I want more than one question, should I open issue per question? How do you prefer it?

**Comment by jfalcou** [comment]
You should not need that using EVE API.
What are you trying to do ?

Also: 1 question == 1 issue.
You can also starts Discussion in the Discussion section.

**Comment by kreuzerkrieg** [comment]
> Also: 1 question == 1 issue. You can also starts Discussion in the Discussion section.

Will start right away!
