### ISSUE TITLE
[BUG] AVX512 tests may balloon out of proportions

### ISSUE THREAD

**Issue by jfalcou** [jfalcou/eve#1187]
Swizzle and shuffle extensive tests on things like vectors of 64/128 chars leads to unbelievably large compile-time and binary size on AVX512.
Those tests should be sliced into multiple targets so we can migrate AVX512 testing to CircleCI.

**Comment by jfalcou** [comment]
Looks like the char x 128 is the culprit at it geenrates as much test that all other char sizes.
What should we do ?

**Comment by DenisYaroshevskiy** [comment]
I think depends on the test. 
Don't do some of the tests for all possible combinations.

**Comment by jfalcou** [comment]
Surrogate of https://github.com/jfalcou/eve/issues/1225
