### ISSUE TITLE
[BUG] write/store inconsistency.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#1265]
We have

`write(it, value)`

but 

`store(value, it)`.

We should fix it.

**Comment by jfalcou** [comment]
so write(value,it) ? It's the simplest fix in term of code to change

**Comment by DenisYaroshevskiy** [comment]
I think so, yes

**Comment by DenisYaroshevskiy** [comment]
https://github.com/jfalcou/eve/pull/1269
