### ISSUE TITLE
[BUG] Reduce has strong opinions about the type it handles

### ISSUE THREAD

**Issue by jfalcou** [jfalcou/eve#1283]
@jtlap and I tried to write some algorithm using reduce and requiring a tuple as an intermediate value.

We wanted this to work: https://godbolt.org/z/s31YPWMjP
but it doesn't cause at some point, reduce try to convert the resultign tuple into a float.

This works but is, I think, too verbose and not intuitive: https://godbolt.org/z/easGb4doT

I think reduce final steps should be amended to handle such cases if possible.

**Comment by DenisYaroshevskiy** [comment]
The example is quite big and unitinuitive for me, sorry.
What do you want to work.

**Comment by DenisYaroshevskiy** [comment]
plus should be commutative and associative. You can't pass 2 different types to plus.

**Comment by DenisYaroshevskiy** [comment]
You see:

```
 required from 'auto eve::detail::butterfly_reduction(Wide, Callable) [with Wide = eve::sse_abi_v0::wide<kumi::tuple<float, float, eve::logical<float> >, eve::fixed<4> >;
```

And the lambda is asymetrical.

**Comment by jfalcou** [comment]
Of course.sorry for the noise.
