### ISSUE TITLE
[BUG] missing constexpr causes constants.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#1353]
missing constexpr for `reverse` and `backward` views cause constatns to appear in the binary.

https://github.com/jfalcou/eve/blob/8663aedb52bfdd79d93043c4a81f1d2bca5cc1a9/include/eve/algo/views/reverse.hpp#L90
https://github.com/jfalcou/eve/blob/8663aedb52bfdd79d93043c4a81f1d2bca5cc1a9/include/eve/algo/views/backward.hpp#L97

Godbolt: https://gcc.godbolt.org/z/oebx9vn6W

**Comment by jfalcou** [comment]
Fixed by https://github.com/jfalcou/eve/pull/1355
