### ISSUE TITLE
[FEATURE] sve: faster iota and masking

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#1359]
There is a native "index" (i.e.) iota instruction on sve. We should utilize it in iota.
We should also use it for `make`

**Comment by jfalcou** [comment]
`iota` do use them.
I don't think make can use it anyhow.

**Comment by DenisYaroshevskiy** [comment]
Like these ones use iota

https://github.com/jfalcou/eve/blob/4057d893e4daf046d77014228367443f4d07c176/include/eve/detail/function/simd/arm/sve/make.hpp#L56
