### ISSUE TITLE
[IMPORTANT] [LICENCE] Move from MIT to BSL licence

### ISSUE THREAD

**Issue by jfalcou** [jfalcou/eve#1367]
Recent discussions with some people interested in using EVE led us to think about moving from MIT to Boost Software Licence.
I'm rather OK with it but we formally need the go from contributors to migrate there. 

So would:
 - [x] @jfalcou myself
 - [x] @jtlap
 - [x] @DenisYaroshevskiy
 - [x] @aguinet
 - [x] @justend29
 - [x] @the-moisrex
 - [ ] @Simran-B
 - [x] @HadrienG2
 - [x] @toughengineer
 - [x] @pauljurczak
 - [x] @JPenuchot
 - [x] @orao

be keen to answer this issue with a YAY or NAY so we can move forward if everybody is OK with the move.
Thanks, everyone

**Comment by JPenuchot** [comment]
YAY

**Comment by DenisYaroshevskiy** [comment]
seems like it is possible to vote for other people. Maybe leave a comment too. I'm good.

**Comment by the-moisrex** [comment]
Yay

**Comment by toughengineer** [comment]
sure

**Comment by justend29** [comment]
YAY

**Comment by HadrienG2** [comment]
YAY

**Comment by jtlap** [comment]
YAY

**Comment by orao** [comment]
Sure, yay! 😁

**Comment by pauljurczak** [comment]
Sure.

**Comment by jfalcou** [comment]
10/12, I guess we all agree it's a go ?
@aguinet ?
@Simran-B  ?
No objections ?

**Comment by aguinet** [comment]
Yay

(sorry for the lag)
