### ISSUE TITLE
[PRE-RELEASE] 2022.09.xx Release

### ISSUE THREAD

**Issue by jfalcou** [jfalcou/eve#1371]
Pre-Release
- [x] Merge #1354 
- [x] Merge #1342
- [x] Move to Boost Software Licence
- [x] Regenerate documentation
- [x] Prepare Changelog
- [x] Fix #1404 

Post-release
- [x] Update SPACK package (including #1379) 
- [x] Update VCPKG package
- [x] Update AUR package
- [x] Update Conan package

**Comment by DenisYaroshevskiy** [comment]
Conan?
