### ISSUE TITLE
[BUG] arm aggregation sucks

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#1394]
Normal code: https://godbolt.org/z/rsKW159E3
Aggreagtion code: https://godbolt.org/z/vnrTe8Tdh

It should just be normal code 4 times

Here is done by hand: https://godbolt.org/z/aGW3GExjK

**Comment by jfalcou** [comment]
Sounds like something wrong with the aggregation unroller.

**Comment by jfalcou** [comment]
Interestingly enough a 2x aggregate is fine

https://godbolt.org/z/Es4anz8f4 vs https://godbolt.org/z/o4T65WzWE

So something breaks the optimizer above a x2 replication

**Comment by jfalcou** [comment]
Apparently, the issue is our recursive system. So maybe specializing for the replication we really care (x2,x4 and x8) should help.

**Comment by DenisYaroshevskiy** [comment]
> Apparently, the issue is our recursive system. So maybe specializing for the replication we really care (x2,x4 and x8) should help.

This does not sound right. Why can't recursion just work?

**Comment by jfalcou** [comment]
I think the optimizer just say fuck it ? I dunno.

**Comment by jfalcou** [comment]
Drive by fixed in  #1766
