### ISSUE TITLE
[FEATURE] movemask for chars with multiplication, arm

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#1395]
I think they have a better top bits.
https://zeux.io/2022/09/02/vpexpandb-neon-z3/

**Comment by jfalcou** [comment]
The latest code use a `__int128` which is a g++ extension.
Is the version before acceptable ?

**Comment by jfalcou** [comment]
Well, they say themselves the non-128 one is enough

**Comment by jfalcou** [comment]
Unless I am mistaken or wrote crap:

https://godbolt.org/z/5bba4Tsev

I don't see any real benefits

**Comment by DenisYaroshevskiy** [comment]
Yeah doesn't look much nicer, thanks for trying it out.
