### ISSUE TITLE
[BUG] Include scheme needs more coherence

### ISSUE THREAD

**Issue by jfalcou** [jfalcou/eve#1404]
Compiling with PCH hides some issues with include order, especially in doc/

**Comment by DenisYaroshevskiy** [comment]
What's eve.hpp? The world?

Would be cool if core tests only included eve/module/core.hpp

And algo tests algo module

**Comment by jfalcou** [comment]
> What's eve.hpp? The world?
Sort of. It is old, maybe we don't even need it. It is meant to be superseded by the main eve module anyway

> Would be cool if core tests only included eve/module/core.hpp
> And algo tests algo module
Yeah. We could work like 1 header per test being the module header.
That's more heavy changes, we can probably do that post-release.

**Comment by jfalcou** [comment]
Restricted scope for now, heavy changes after the release

**Comment by jfalcou** [comment]
OK after a bunch of state, we need to clean that up. COmpiling doc tests without PCH reveals a bunch of oversight.
