### ISSUE TITLE
[BUG] Several cpp files don't compile and are not part of the build

### ISSUE THREAD

**Issue by Klaim** [jfalcou/eve#1503]
**Describe the bug**
Some source files are not built and contain non-compiling code.

See: 
- [test/doc/coretest/doc/core/saturated/minus.cpp/saturated/minus.cpp](https://github.com/jfalcou/eve/blob/main/test/doc/core/saturated/minus.cpp#L1-L3)
- https://github.com/jfalcou/eve/blob/main/test/unit/module/complex/signnz.cpp#L23

**Comment by jfalcou** [comment]
Fixed in #1505  pending CI cycling
