### ISSUE TITLE
[FEATURE] More algo-like wide level functions

### ISSUE THREAD

**Issue by jfalcou** [jfalcou/eve#1524]
We already have zip, all, any, reduce working on wide for various scenarii.
We also have detail::map which is a mess and shoudl be simplified if we could have it as a regular function.

I think we should move map form detail to eve and give it the proper name: transform so we can properly optimize it and have a full 1-1 set of algo-like operations on single wide.

Maybe some other coudl be used ?

**Comment by DenisYaroshevskiy** [comment]
Do users really need map on a wide? I mean that's slow nd bad by defenition

**Comment by jfalcou** [comment]
you may want to apply a non vectorizabel scalar function on some wide.
Now, maybe we cna just refurbish th einner map as we did for othe detail like dispatchable functions.
