### ISSUE TITLE
[Question] How to convert range of scalar to range of vector?

### ISSUE THREAD

**Issue by octopus-prime** [jfalcou/eve#1534]
Your data is given as a range of scalars.
Now you want to process the data as range of vectors.
How to covert these ranges?

```
void foo() {
  using S = std::int16_t;
  using V = eve::wide<S>;
  constexpr auto N = 256;
  constexpr auto M = N / V::size();
  S biases[N];
  V accu[M];

  eve::algo::copy(biases, accu); // how to make biases a range of V?
}
```

**Comment by DenisYaroshevskiy** [comment]
What would be your end goal? If I know that, I can better help you.

Because we work with generic cases, we usually assume existance of a tail - therefore there is no "range" of wides.
If you have a divisible by V::size() range, you can ofcourse do a `memcpy`, a `reinterpret_cast` or use ranges::v3

https://godbolt.org/z/sT36Ta99K

If you want to stay withing what we, you want to use our algorithms.
Our algorithms support `divisible_by_cardinal` trait that can come in handy. If you also align both ends, we will deduce that automatically.

Here is a for_each example, it's the most generic, you might wanna use some more special algorithm.

https://godbolt.org/z/EKq9fK87M

**Comment by octopus-prime** [comment]
Thanks for reply!

"What would be your end goal? If I know that, I can better help you."
Express NNUE in terms of eve.

See https://github.com/glinscott/nnue-pytorch/blob/master/docs/nnue.md#implementation

As your can see
``````
eve::algo::copy
```
should replace this code
```
    // Load bias to registers and operate on registers only.
    for (int i = 0; i < num_chunks; ++i) {
        regs[i] = _mm256_load_si256(&layer.bias[i * register_width]);
    }
```

So as first evaluation I would like to convert
this code
```
    // Load bias to registers and operate on registers only.
    for (int i = 0; i < num_chunks; ++i) {
        regs[i] = _mm256_load_si256(&layer.bias[i * register_width]);
    }

    for (int a : active_features) {
        for (int i = 0; i < num_chunks; ++i) {
            // Now we do 1 memory operation instead of 2 per loop iteration.
            regs[i] = _mm256_add_epi16(regs[i], &layer.weight[a][i * register_width]);
        }
    }

    // Only after all the accumulation is done do the write.
    for (int i = 0; i < num_chunks; ++i) {
        _mm256_store_si256(&new_acc[perspective][i * register_width], regs[i]);
    }
```

into eve-code.

**Comment by octopus-prime** [comment]
I tried this
```
template <typename T, size_t N>
constexpr auto span_cast(std::span<const T, N> s) noexcept {
  using U = eve::wide<T>;
  constexpr auto M = N / U::size();
  return std::span<const U, M>((U const *) s.data(), M);
}
```
to cast the biases-range - without success...

```
  eve::algo::copy(span_cast<S, N>(biases), accu);
```
does not compile.

So I wonder if there is something out-of-the-box in eve?

**Comment by octopus-prime** [comment]
I saw your examples...
Nevertheless
```
auto rng(std::span<const int16_t> in) {
  return in | std::ranges::views::chunk(eve::wide<int16_t>::size())
            | std::ranges::views::transform([](auto x) { return eve::wide<int16_t>(x); });
}

void question() {
  using S = std::int16_t;
  using V = eve::wide<S>;
  constexpr auto N = 256;
  constexpr auto M = N / V::size();
  S biases[N];
  V accu[M];

  eve::algo::copy(rng(biases), accu);
}
```
does not compile

**Comment by DenisYaroshevskiy** [comment]
I see, no worries.

# 1. Ansering your question.

eve algorithms operate on ranges of elements, not ranges of wides. so eve::algo::copy(rng(biases), accu) won't work.

that code seems buggy (it mixes mm128 and mm256) - but you can just replace the:

* `16` with `eve::wide<std::int16_t>::size()`
* `__m128i` with `eve::wide<std::int16_t>` 
*  `_mm256_load_si256` with `eve::load(ptr, eve::as<eve::wide<std::int16_t>>{})`;
* `reg[i] = _mm256_add_epi16(reg[i],` with `+=`
* `_mm256_store_si256` with `eve::store(reg[i], ptr)`

Assuming that the size is divisible by 64 or smth, this should work.

# I think you can do better

I don't quite know where all of the arrays come from in that code but here is how I'd do it

https://godbolt.org/z/qeEfsdqzK

**Comment by octopus-prime** [comment]
True - an error in the doc. But the rest of the doc is just amazing

:-)

We start to come to the main point (for me).
You suggested: use auto-vetorization
So I tried - with success - but only sometimes

The example (at end) show compiler output not using avx at all
In other experiments the code looks perfect.

for fast nnue accumulation is said: do it in registers only
so output should look like this
```
vmovdqa 0xa0(%rsp),%ymm9 (x16)
L:
vpaddw (%rax),%ymm9,%ymm9  (x16)
cmp    %r8,%rdx
jne    L
vmovdqa %ymm9,0xa0(%rsp)  (x16)
```

but often the output produced looks like
```
vmovdqa 0xa0(%rsp),%ymm9 (x16)
L:
vpaddw (%rax),%ymm9,%ymm9  (x16)
vmovdqa %ymm9,0xa0(%rsp)  (x16)
cmp    %r8,%rdx
jne    L
vmovdqa %ymm9,0xa0(%rsp)  (x16)
```
note the extra store in the loop

So the main issue is:
It is difficult to predict compiler output
No clue what triggers the differences
Impossible to produce fasted code out-of-the-box

So the hope was:
Express NNUE in terms of eve.
This will produce fastest possible code - out-of-the-box, every-time.
Stuff will become more readable - more maintainable
All the boiler-plate will be hidden by eve (e.g. https://github.com/official-stockfish/Stockfish/blob/fc5b59b88bae00b7e74bbad0de7c3c33136937cf/src/nnue/nnue_feature_transformer.h)

Here the example
https://godbolt.org/z/sfbqoTe5T
note
```
.L15:
        movzx   ecx, WORD PTR [rdx]
        add     WORD PTR [rax], cx
        add     rax, 2
        add     rdx, 2
        lea     rcx, [rsp+1056]
        cmp     rax, rcx
        jne     .L35
```
lol

So i will try this load/store stuff... Tanks a lot!

**Comment by DenisYaroshevskiy** [comment]
I'm not sure I understood everything you said but it seems like I answered your question - so I will close the issue.
Feel free to reopen - or create a new one if I misread that.
