### ISSUE TITLE
[BUG] HPX tags on main branch interfere with AUR package version detection

### ISSUE THREAD

**Issue by JPenuchot** [jfalcou/eve#1539]
**Describe the bug**

The current AUR package uses the last tag to determine the package version automatically. Adding HPX tags to the main branch interferes with that automatism.

**To Reproduce**

Build the AUR package for EVE: https://aur.archlinux.org/packages/eve-git/

```sh
git clone https://aur.archlinux.org/eve-git.git
cd eve-git
makepkg
```

**Expected behavior**

The expected reported version in `PKGBUILD` should be the last EVE version `2022.09.1`, but instead it reports `hpx.v1.9.0`.

**Setup:**

 - OS: ArchLinux btw

**Suggested fixes:**

- Coordinate EVE releases and HPX tags, ensuring the last tag is the actual EVE release,

or,

- create a separate branch for HPX tags.

**Comment by jfalcou** [comment]
the HPX tags are in the experimental/hpx branch so I am confused

**Comment by JPenuchot** [comment]
I just found a better solution: git tags can be filtered with a regex, I'll just use on my side to exclude HPX tags instead.
