### ISSUE TITLE
[FEATURE] eve::fma should support a different type (maybe?)

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#1542]
This comes from #1541

in tansfrom_reduce, if I use `[fuze_operatons]` - there is no reasonable place to put conversion in.
You would like to apply `map` before conversion and `add` after.

This is how it looks now:

```
        auto mapped = map_op(loaded);
        auto cvt    = eve::convert(mapped, eve::as<element_type_t<SumWide>> {});
        sums[idx()] = add_op(sums[idx()], if_else(ignore, cvt, zero));
```

So what I will do is not apply conversion:

```
 if constexpr ( traits_type::contains(fuse_operations))) {
   sums[idx()] = map_op(loaded, sums[idx()]);
 }
```

but that won't work with the most widely used op. 

What should happen is:

```
fma(float, float, double)
```

should work: convert float to double and fma that.

**Comment by jfalcou** [comment]
well, in the general case or for scalar specifically ?
Having auto covnersion on wide operations is a huge can of worms

**Comment by DenisYaroshevskiy** [comment]
In general case. For the same cardinal.

If you look at tests, I had to write this:

```
 []<typename Sum, typename N>(auto x, eve::wide<Sum, N> sum) {
          return eve::convert(x, eve::as<Sum>{}) + sum; }, init);
  }
```

I think fma can do that out of the box. If you feel that people should do this explicitly, that's ok too.

they can always `[eve::algo::force_type<T>]` or smth

**Comment by jfalcou** [comment]
After discussing with @jtlap, a good compromsie woudl be to have a `promote` decorator

`promote(fma)(x,y,z)` computes fma as if all their parameters have been converted to the common type of the element type of the parameter.

THis can then later be applied to more functions. It doesn't break current FMA, is controllable and easy to use in the afformentionned use case.

**Comment by DenisYaroshevskiy** [comment]
What does it do?

**Comment by jfalcou** [comment]
```c++
using c_t = std::common_type_t<element_type_t<T>,element_type_t<U>,element_type_t<V>>;

promote(fma)(T t,U u,V v) ==> fma( convert(t,as<c_t>()), convert(u,as<c_t>()), convert(v,as<c_t>()));
```

**Comment by DenisYaroshevskiy** [comment]
Ok, let's do that. Only eve common type

**Comment by jfalcou** [comment]
Promote is available on all FMA like operation now
