### ISSUE TITLE
modify the behavior ofswap_adjacent_groups for limiting conditions 

### ISSUE THREAD

**Issue by jtlap** [jfalcou/eve#1595]
up to now swap_adjacent groups is not defined if the group size G is equal to 0 but is if it equal to N

for me it will be better that with size 0 it will act as identity (nothing to swap) return v.
but for N it is not clear that it will be defined at all because there is nothing to swap with the full wide.
The other possibility is to say that if there is nothing to swap with consider it is null and return zero(as(v))

the case N is not so important but 0 is. It will be useful for fft.

Also, swap_adjacent_groups is not documented at all. 
It will be pleasant if all functions were properly documented.
Also,I propose that swap_adjacent_groups  it will be moved in core rather than in api 
as the tests are in core.
Finally, I think that with no loss of comprehension the name could simply be swap_adjacent or swap_adjacents

**Comment by DenisYaroshevskiy** [comment]
It's a shuffle so it's with other shuffles. We have q shuftle rewrite project but we didn't get to it yet.

At the moment not all shuffles accept group size, so that's why group.

I very much dislike zero for group size zero. If group size zero is supported, it should be a noop

**Comment by jtlap** [comment]
It is what I meant:  "for me it will be better that with size 0 it will act as identity (nothing to swap) return v." 
it is noop that I would like.

for N the noop is unexpected. If you don't like zero we can requires G<cardinal instead of G<=cardinal

For the name what can swap_adjacents mean except swap adjacent groups ? I just say that the name can be shorter with no confusion added

**Comment by DenisYaroshevskiy** [comment]
* It can mean swap_adjacent elements not groups
* group size 0 being identity is ok with me
* Group size N being identity is consistent. You swqp adjacent groups of size N and nothing happens

**Comment by jtlap** [comment]
ok for me
but (just to say) so why require G<= N as the argument do do nothing can be the same

**Comment by jtlap** [comment]
Denis, will you want me to do it (modification for the zero case and doc) or do you prefer to do it yourself ?

**Comment by DenisYaroshevskiy** [comment]
Either works. I don't know when I get to it myself

**Comment by jtlap** [comment]
ok I'll do it

**Comment by DenisYaroshevskiy** [comment]
Hi

I'm sorry, shufling groups size 0 does not work. swap_adjacent for G == T::size() I will dsiable as well.
