### ISSUE TITLE
[BUG] `Wuninitialized`

### ISSUE THREAD

**Issue by chriselrod** [jfalcou/eve#1619]
**Describe the bug**
GCC yields uninitialized warnings when we don't specify an `else` on the conditional, as `r_t that` is then returned by `src`.
https://github.com/jfalcou/eve/blob/cb6cc16813d38b9bea85765b6f38db39db6235ad/include/eve/module/core/regular/impl/simd/x86/load.hpp#L63-L68C21
However, Clang fails to optimize well if we do set an altnerate.

**To Reproduce**
Minimal example of the error:
https://godbolt.org/z/evoKqYTrf

Less minimal example of an error, showing Clang doing a fairly good job optimizing the example away:
https://godbolt.org/z/oo3zYW5sG
Swapping the comment to enable the alternate makes GCC happy, but Clang's codegen is now poor:
https://godbolt.org/z/vecoo554P

I haven't tested to confirm this, but I suspect using the `maskz` variants of the instructions in case of no conditionals would fix this problem. That is, use `_mm512_mask_loadu_pd` if there is an alternate, and `_mm512_maskz_loadu_pd` otherwise.
I could prepare a PR (in which case I could test).

**Comment by DenisYaroshevskiy** [comment]
Thank you for rasing this. I'm amazed that ci didn't catch this, we should test with Wall Werror.

If you want to try and fix it, I can support you in that. Otherwise I will have a more indepth look in a bit

**Comment by DenisYaroshevskiy** [comment]
Looked a bit more. 

1. In your example clang and gcc codegen is identical, it is just you forgot to pass -DNDEBUG: https://godbolt.org/z/xK66eWhWT

2. mmaskz can be optimized from not z version by clang /gcc
https://godbolt.org/z/ocE8ena66

3. msvc ofc can't optimize anything, but I don't know if even we get to that, we care about working around msvc poor optimization https://godbolt.org/z/4x8G4zGs5

4. I also quickly checked at https://uops.info/table.html If I'm reading that right, there is no advantage to using z or no z version.

Hmm. I'm a bit on the fence here.
I think maskz is a good option. And in order to help with debuggability, perhaps in NDEBUG mode we should always load with some poisoned data in else_.

**Comment by chriselrod** [comment]
1. Identical is really bad for Clang. Without using the `.else_(0)`, clang optimizes most of it away:
```asm
test(double*, double*, long):                           # @test(double*, double*, long)
        mov     rax, -1
        shlx    rax, rax, rdx
        not     al
        kmovd   k1, eax
        vmovupd zmm0 {k1} {z}, zmmword ptr [rdi]
        vmovupd zmmword ptr [rdi] {k1}, zmm0
        vzeroupper
        ret
test(double*, double*):                            # @test(double*, double*)
        ret
```
Yet if we add `.else_(0)` with `DNDEBUG`, we get
```asm
test(double*, double*, long):                           # @test(double*, double*, long)
        mov     rax, -1
        shlx    rax, rax, rdx
        not     al
        kmovd   k1, eax
        vmovupd zmm0 {k1} {z}, zmmword ptr [rdi]
        vmovupd zmm1 {k1} {z}, zmmword ptr [rsi]
        vaddpd  zmm2, zmm1, zmm0
        vmovupd zmmword ptr [rdi] {k1}, zmm2
        vmovupd zmm2 {k1} {z}, zmmword ptr [rdi]
        vmulpd  zmm2, zmm2, zmm1
        vdivpd  zmm2, zmm2, zmm0
        vmovupd zmmword ptr [rdi] {k1}, zmm2
        vmovupd zmm2 {k1} {z}, zmmword ptr [rdi]
        vmulpd  zmm0, zmm2, zmm0
        vdivpd  zmm0, zmm0, zmm1
        vsubpd  zmm0, zmm0, zmm1
        vmovupd zmmword ptr [rdi] {k1}, zmm0
        vzeroupper
        ret
test(double*, double*):                            # @test(double*, double*)
        mov     al, 127
        kmovd   k1, eax
        vmovupd zmm0 {k1} {z}, zmmword ptr [rdi]
        vmovupd zmm1 {k1} {z}, zmmword ptr [rsi]
        vaddpd  zmm2, zmm1, zmm0
        vmovupd zmmword ptr [rdi] {k1}, zmm2
        vmovupd zmm2 {k1} {z}, zmmword ptr [rdi]
        vmulpd  zmm2, zmm2, zmm1
        vdivpd  zmm2, zmm2, zmm0
        vmovupd zmmword ptr [rdi] {k1}, zmm2
        vmovupd zmm2 {k1} {z}, zmmword ptr [rdi]
        vmulpd  zmm0, zmm2, zmm0
        vdivpd  zmm0, zmm0, zmm1
        vsubpd  zmm0, zmm0, zmm1
        vmovupd zmmword ptr [rdi] {k1}, zmm0
        vzeroupper
        ret
```
The latter is the same as GCC, but is substantially worse than Clang got without `.else_(0)`.

2. That is unfortunate. See here how Clang generates substantially better code with the undef than it does with maskz (which is the same as `.else_(0)`, as you noted): https://godbolt.org/z/E6on4TqGK

Because clang was generating `{z}` loads with the undef, I hoped `maskz` would be the same as `undef`. I was too optimistic.

3 & 4. Ha. My concern was over Clang's ability to delete everything. Note my test function is a no-op (given appropriate associativity flags). Also, msvc really doesn't like the undef. https://godbolt.org/z/svcrs6oE3

**Comment by DenisYaroshevskiy** [comment]
1. Identical is really bad for Clang. Without using the .else_(0), clang optimizes most of it away:
Ah - I see - it's a noop with ffast math. It should all go waya in theory.

2. Ok that's an extra motivation for z.

Do you want to add the `maskz` fix or do you want me to do it? I am OK either way.

If you want to try, here is the build instructions https://jfalcou.github.io/eve/dev_cmake.html
And you can ping me any time when something doesn't work.

**Comment by DenisYaroshevskiy** [comment]
I know why we didn't see it, compiler doesn't show warnings in precompiled headers.

Also, can I ask what you are trying to do? Maybe there's an out of the box solution.

**Comment by chriselrod** [comment]
> Do you want to add the maskz fix or do you want me to do it? I am OK either way.

Because clang generates better code currently, what do you think about using `#ifdef __clang__`?

> I know why we didn't see it, compiler doesn't show warnings in precompiled headers.

Ah. In the example I tried, gcc would lock up the terminal for several minutes due to the flood of error messages, while clang would compile in a few seconds.
IO dominated the compile times.

Unless there is an automated option, I shouldn't have been using pch, so I'm not sure why clang didn't warn, when it did in your godbolt example from earlier.

> Also, can I ask what you are trying to do? Maybe there's an out of the box solution.

My actual example has lots of repeated/matching store->loads with the same masks.
It isn't a no-op under fastmath, I just did that for my example here to make the difference much more obvious.

The repeated store->loads add a lot of latency and severly hurt performance, and it seemed like a compiler really shouldn't have had a problem getting rid of these matching pairs.

But it probably requires some non-trivial analysis specifically for vector operations.
That is, the masked-off lanes could change value, so it'd have to check all uses to make sure these are never used, i.e. that they are also masked off in stores.

This wouldn't have been necessary in the first of the extra store/load pairs, as we did two masked loads, and then added them. That preserves the zeros in the masked off lanes prior to the store->load, which resets them to zero.


More background:
I was playing with using eve to vectorize a small expression template library.
Then for a demo, I used that to implement forward-mode auto diff, where vectors of partials are statically sized vectors.
E.g.
```c++

template <class T, size_t N> class Dual {
  T val{};
  SVector<T, N> partials{};

public:
  using val_type = T;
  static constexpr size_t num_partials = N;
  constexpr Dual() = default;
  constexpr Dual(T v) : val(v) {}
  constexpr Dual(T v, ptrdiff_t n) : val(v) { partials[n] = T{1}; }
  constexpr Dual(T v, SVector<T, N> g) : val(v), partials(g) {}
  constexpr Dual(std::integral auto v) : val(v) {}
  constexpr Dual(std::floating_point auto v) : val(v) {}
  constexpr auto value() -> T & { return val; }
  constexpr auto gradient() -> SVector<T, N> & { return partials; }
  [[nodiscard]] constexpr auto value() const -> const T & { return val; }
  [[nodiscard]] constexpr auto gradient() const -> const SVector<T, N> & {
    return partials;
  }
  constexpr auto operator-() const -> Dual { return Dual(-val, -partials); }
  constexpr auto operator+(const Dual &other) const -> Dual {

    return {val + other.val, partials + other.partials};
  }
  constexpr auto operator-(const Dual &other) const -> Dual {
    return {val - other.val, partials - other.partials};
  }
  constexpr auto operator*(const Dual &other) const -> Dual {
    return {val * other.val, val * other.partials + other.val * partials};
  }
  constexpr auto operator/(const Dual &other) const -> Dual {
    return {val / other.val, (other.val * partials - val * other.partials) /
                               (other.val * other.val)};
  }
  constexpr auto operator+=(const Dual &other) -> Dual & {
    val += other.val;
    partials += other.partials;
    return *this;
  }
  constexpr auto operator-=(const Dual &other) -> Dual & {
    val -= other.val;
    partials -= other.partials;
    return *this;
  }
  constexpr auto operator*=(const Dual &other) -> Dual & {
    val *= other.val;
    partials = val * other.partials + other.val * partials;
    return *this;
  }
  constexpr auto operator/=(const Dual &other) -> Dual & {
    val /= other.val;
    partials << (other.val * partials - val * other.partials) /
                  (other.val * other.val);
    return *this;
  }
  constexpr auto operator+(double other) const -> Dual {
    return {val + other, partials};
  }
  constexpr auto operator-(double other) const -> Dual {
    return {val - other, partials};
  }
  constexpr auto operator*(double other) const -> Dual {
    return {val * other, other * partials};
  }
  constexpr auto operator/(double other) const -> Dual {
    return {val / other, partials / other};
  }
  constexpr auto operator+=(double other) -> Dual & {
    val += other;
    return *this;
  }
  constexpr auto operator-=(double other) -> Dual & {
    val -= other;
    return *this;
  }
  constexpr auto operator*=(double other) -> Dual & {
    val *= other;
    partials *= other;
    return *this;
  }
  constexpr auto operator/=(double other) -> Dual & {
    val /= other;
    partials /= other;
    return *this;
  }
  constexpr auto operator==(const Dual &other) const -> bool {
    return val == other.val; // && grad == other.grad;
  }
  constexpr auto operator!=(const Dual &other) const -> bool {
    return val != other.val; // || grad != other.grad;
  }
  constexpr auto operator==(double other) const -> bool { return val == other; }
  constexpr auto operator!=(double other) const -> bool { return val != other; }
  constexpr auto operator<(double other) const -> bool { return val < other; }
  constexpr auto operator>(double other) const -> bool { return val > other; }
  constexpr auto operator<=(double other) const -> bool { return val <= other; }
  constexpr auto operator>=(double other) const -> bool { return val >= other; }
  constexpr auto operator<(const Dual &other) const -> bool {
    return val < other.val;
  }
  constexpr auto operator>(const Dual &other) const -> bool {
    return val > other.val;
  }
  constexpr auto operator<=(const Dual &other) const -> bool {
    return val <= other.val;
  }
  constexpr auto operator>=(const Dual &other) const -> bool {
    return val >= other.val;
  }
};
```

These may be nested if we're interested in higher order derivatives.

I also wanted the memory layout to be compatible with Julia's `ForwardDiff.jl`, which uses a packed layout. This means we can't do the obvious thing and store SIMD vectors for our inner most partial derivatives directly (by inner most, I mean when `std::floating_point<T>`, for outer ones, `T` would itself be `Dual`).

My long term goal is to work on LLVM loop optimization for optimizing the libraries, but short term, I thought it'd be fun to play with eve (and if results went well there, that could be a baseline for the loop optimizer).

Part of the motivation there was that without vectorizing, the C++ code using the dual numbers compiled several times faster than Julia for a simple problem (80 seconds for Julia, 20s for Clang), while using many fewer lines of code that were also easier to read. It also ran several times faster (e.g. 780us for Julia, 220us for Clang).

Yet, when looking at the assembly, C++'s was extremely bad. Julia's obviously wasn't good either, but the performance difference came from RAII >>>> Julia's garbage collector.
The difference in lines of code also came from (1) painstakingly trying to work around the GC in Julia, and (2) less sophisticated templating system in Julia for fusing operations, meaning more had to be written out in manual loops to avoid allocations.

I figured if it was easy to get another several factor improvement in the C++ code, it'd be interesting to try.
For reference, [templating](https://github.com/LoopModels/Math/blob/eve/include/Math/ArrayOps.hpp), [wrapping eve](https://github.com/LoopModels/Math/blob/eve/include/Math/SIMD.hpp).
There may be better ways to do this, of course.

Why not use something like Eigen?
Because my actual use case is currently using integer arithmetic for everything, and hence needs integer-preservig algorithms.
Although I am thinking about switching to using `double` instead of `int64_t` for representing integers. `double` is exact for all integers with absolute value `<= 2e53`, with the advantage of setting [FE_INEXACT](https://en.cppreference.com/w/cpp/numeric/fenv#:~:text=The%20floating%2Dpoint%20environment%20is,environment%20from%20the%20parent%20thread) if they ever round, making cheap checks easy, compared to using SIMD integer arithmetic.

**Comment by DenisYaroshevskiy** [comment]
> Because clang generates better code currently, what do you think about using #ifdef __clang__?

I'm a bit confused with this - did you try maskz? Because the correct solution seems to be to use maskz.

> Ah. In the example I tried,  ...

this is mostly a note for us - why our ci didn't trigger on this.

> More background: ...

There is a lot that I unfortunately don't quite follow. But, looking at your class, did you consider padding  your array to 32 or 64 bytes? Then you won't push into an insane latency of masked loads.

If I was writing this, I'd do smth like:

```
template <class T, size_t N> class Dual
  requires (N < 64 / sizeof(T)) 
 {
  std::array<T, 64 / sizeof(T)>
```

And then used the first or last element as val.

**Comment by chriselrod** [comment]
> I'm a bit confused with this - did you try maskz? Because the correct solution seems to be to use maskz.

I tried it: https://godbolt.org/z/E6on4TqGK

**Comment by chriselrod** [comment]
> There is a lot that I unfortunately don't quite follow. But, looking at your class, did you consider padding your array to 32 or 64 bytes? Then you won't push into an insane latency of masked loads.

I wanted the same memory layout as Julia's `ForwardDiff.Dual` uses, for the same of comparing a Julia implementation of a function with `ccall`ing C++ code.

**Comment by DenisYaroshevskiy** [comment]
> I tried it: https://godbolt.org/z/E6on4TqGK

Hmm. Maybe you want to have your own load function that returns you an eve::wide for now? If unutialized is helpful, maybe then we should disable the warning there.

> I agree that padding would be better, but the Julia library uses dense.

Do you know the N in your example by any chance? latency 9 is a lot, maybe if the length is known, some other cobination would be good

**Comment by chriselrod** [comment]
You can look at this: https://godbolt.org/z/vYG6eK98z
And see the difference replacing `zeroinitializer` with `undef` makes for Clang.

> latency 9 is a lot

That is a lot of latency, but seems to only be 1 extra cycle compared to the unmasked variant (9,9,6 vs 8,8,5). Measured throughput is also a little worse, but fairly comparable.
https://uops.info/html-instr/VMOVUPD_ZMM_M512.html
https://uops.info/html-instr/VMOVUPD_ZMM_K_M512.html
That (and benchmarks) are why I'm also a big fan of predicated epilogue vectorization (which eve dpes, but neither LLVM or GCC, currently do).

> Do you know the N in your example by any chance? 

`N` is chosen dynamically by our program; there is no reason we can't round the inner-most `N` (i.e., the one where `T = double`) up to the next multiple of SIMD vector width, or next power of 2 if `N` is smaller.

I'll make the case that this is worth doing.

> Are you specializing for double then?

The `SVector` type's arithmetic operations are specialized for `std::integral<T> || std::floating_point<T>`.
