### ISSUE TITLE
[FEATURE] gcc nopch on CI

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#1625]
GCC warnings are not similar to clang warnings and we completly miss them when compiling with a PCH.

OR: we can make PCH build produce warnings. I asked in a cmake channel on how to do it, since googling is not obvious.

**Comment by DenisYaroshevskiy** [comment]
Maybe, if we define CMAKE_PCH_PROLOGUE="" this will help.

**Comment by jfalcou** [comment]
Tested and it doesn't change the generated PCH header :/

**Comment by DenisYaroshevskiy** [comment]
> Tested and it doesn't change the generated PCH header :/

Do you think it should? Could you test if maybe warnings show up?
