### ISSUE TITLE
[BUG] find_simd looks broken

### ISSUE THREAD

**Issue by tilir** [jfalcou/eve#1632]
**Describe the bug**
find_simd looks broken

**To Reproduce**
[Simple godbolt reproducer](https://godbolt.org/z/Pq53ToGKa)

Code:

```
#include <eve/module/core.hpp>
#include <eve/module/algo.hpp>

int find_simd(const int *a, int n, int x) {
  auto sub = eve::algo::as_range(a, a + n);  
  auto pos = eve::algo::find_if(sub, x);
  if (pos == sub.end())
    return -1;
  return pos - sub.begin();
}
```

**Expected behavior**
I expect this to compile.

**Setup:**
 - Compiler and compiler's version: g++12
 - OS: Ubuntu
 - Processor Architecture x86_64
 - Instructions Set used AVX

**Additional context**

**Comment by tilir** [comment]
Sorry stupid typo

**Comment by DenisYaroshevskiy** [comment]
Horray, someone is using algo!
