### ISSUE TITLE
[BUG] Install destination should not depend on the version number

### ISSUE THREAD

**Issue by JPenuchot** [jfalcou/eve#1672]
**Describe the bug**

Here: https://github.com/jfalcou/eve/blob/3ba995261fd56bde4967abd94a7ec50fcecf03e1/cmake/config/eve-install.cmake#L8

EVE is being installed in a version-dependent directory. It should be installed directly in the installation directory instead like any other libraries. CMake variables already allow changing the install destination if required by the user.

**To Reproduce**

Install EVE

**Expected behavior**

The `eve/` include folder should be installed directly in the include installation directory.

**Comment by jfalcou** [comment]
Fixed
