### ISSUE TITLE
[BUG] gcc permissive issue on avx512

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#1683]
/opt/compiler-explorer/libs/eve/trunk/include/eve/detail/shuffle_v2/simd/x86/shuffle_l2.hpp:96:41: error: invalid conversion from 'int' to '_MM_PERM_ENUM' [-fpermissive]
   96 |     else return _mm512_shuffle_epi32(x, m);

**Comment by jfalcou** [comment]
This affects https://github.com/jfalcou/kyosu/pull/50
Will fix it
