### ISSUE TITLE
Add an `eve::wide` iota factory/constructor

### ISSUE THREAD

**Issue by ldalessa** [jfalcou/eve#1686]
When I'm processing loops I often have code that is a function of the induction variable. In SIMD code this means that I need a vector that represents a contiguous slice of the induction space. As an example, something like:

```c++
for (int i = 0; i < n; i += vec.size()) {
    auto vindex = eve::wide<T>([i](int j, auto) { return i + j; });
}
```

This would be a lot simpler if there was an `iota` factory or constructor for the wide template.

```c++
for (int i = 0; i < n; i += vec.size()) {
    auto vindex0 = eve::iota<T>(i, i + vec.size());
    auto vindex1 = eve::wide<T>(eve::iota, i, i + vec.size());
}
```

Something along those lines. It would be convenient if it inferred `T` from the index type, but it's necessary that I be able to set `T` explicitly because the cardinality might be wrong. I don't necessarily need a single-argument version of this, nor does it feel appropriate to have one in general as these are bounded ranges and I don't want to decide if the passed variable is the beginning or the end. I would prefer it to be the beginning if you really want one.

**Comment by DenisYaroshevskiy** [comment]
I missed your question somehow.

We usually do

```
eve::wide<T> x { [](int i, int) { return i; } };
```

Granted, I agree we should expose smth.
I think `eve::iota(eve::as<wide<T>>)` would be the style to do it.

NOTE: detail::linear_ramp should really be renamed in iota and used for this.

**Comment by ldalessa** [comment]
This isn't blocking me, so it's not urgent. To me, the algorithm versions are very difficult to read and understand and modify and debug, relative to loopy code, so it will take me a while to figure such things out.

**Comment by DenisYaroshevskiy** [comment]
Up to you.

**Comment by DenisYaroshevskiy** [comment]
It's in main (on godbolt tomorrow)

https://jfalcou.github.io/eve/group__core__constants_ga201aa31a6833222e1640130387cbba48.html#ga201aa31a6833222e1640130387cbba48

how are you consuming the library?
