### ISSUE TITLE
[BUG] Doxygen missing docs (highlighted)

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#1696]
https://github.com/jfalcou/eve/blob/a793cfd14bf0d5ade22dadde4586d2a0881ab008/include/eve/module/algo/views/iota.hpp#L15

**Comment by jfalcou** [comment]
https://jfalcou.github.io/eve/group__views_gac775cd27d2cf90ff76710e45c8e5e1d5.html#gac775cd27d2cf90ff76710e45c8e5e1d5 
is back
