### ISSUE TITLE
[BUG] eve::negate does not compile

### ISSUE THREAD

**Issue by foolnotion** [jfalcou/eve#1732]
**Describe the bug**
I assume `eve::negate` usage is the same as other arithmetic operations like `eve::abs`, `eve::sqr`, etc. (link to [documentation](https://jfalcou.github.io/eve/group__core__arithmetic_gad0dd8ae2cec6f99c1523ec4871efce3c.html#gad0dd8ae2cec6f99c1523ec4871efce3c))

**To Reproduce**
https://godbolt.org/z/cKoKbP4KM

**Expected behavior**
Negation works properly

**Setup:**
 - Compiler and compiler's version: clang-17.0.1
 - OS: NixOS Linux
 - Processor Architecture: x86-64 (Ryzen 5950X)
 - Instructions Set used: AVX2 (I think?)

**Additional context**
The code snippet does not compile with `gcc-13.2` either. Both `eve-20230215` and `eve-trunk` have this issue.

Using `std::negate{}` instead of `eve::negate` works properly (but perhaps less efficient).

**Comment by jfalcou** [comment]
The eve::negate function is a  binary function that carry over the sign of one of its param to the other

https://jfalcou.github.io/eve/group__core__arithmetic_gad0dd8ae2cec6f99c1523ec4871efce3c.html#gad0dd8ae2cec6f99c1523ec4871efce3c

**Comment by jfalcou** [comment]
We could probably add an unary negate to mimic std negate

**Comment by foolnotion** [comment]
my bad! I should've read the documentation more carefully! I was quite convinced it should behave the same as `std::negate`

**Comment by jfalcou** [comment]
We will add an overload to -x

**Comment by jtlap** [comment]
negate is named here according some x86 simd intrinsics

**Comment by jtlap** [comment]
I think you can already use eve::minus(x) in place of -x.
The only differrence is that if x is scalar (not wide) there is no automatic C++ promotion
For instance short to int.

**Comment by jfalcou** [comment]
I think we can however also align with std behavior for the unary case ?

**Comment by jtlap** [comment]
I don't know: look at the doc of std::negate. It's a part of <functional>

**Comment by jfalcou** [comment]
Oh I forgot about minus.
However we have a case where expected behavior w/r to an existing name is co fusing. So we do need to think about it.

**Comment by foolnotion** [comment]
The more I think about it, `negate` seems like a strange name for this function:

$$
    f(x, y) = x \cdot \text{sgn}(y)
$$

For example $f(x, y) = x$ for positive $y$ (is this really a negate?). 

I would maybe call it `eve::mul_sgn` or maybe even `eve::sign` (as a complement to the already existing unary `eve::sign`).

For the unary case, I guess some alternatives could be:

- `eve::zerominus` (since there already is an `eve::oneminus`)
- `eve::flip_sign`

**Comment by jfalcou** [comment]
Sign has a completely different semantic as it returns the sign bit.
The negate name comes from the intrinsic name most arch use for this.
For now, I will amen the doc to cross reference negate and unary minus and put some warnings there.
