### ISSUE TITLE
Performance in DEBUG mode

### ISSUE THREAD

**Issue by dpronin** [jfalcou/eve#1740]
Guys, please tell me if it is expectable that performance of eve::algo::copy() is dramatically lower than the corresponding algorithm from STL std::ranges::copy() in case we compile with -O0 and copy one range of bytes (uint8_t) to another with virtually contiguous memory (for example, I copy one std::span to another)? Is there someone who has observed this behaviour?
In both cases memcpy, as a part of glibc, is compiled with -O2 and work under the hood if you call it. So, if you call memcpy within internals of eve::algo::copy() it must work as well as std::ranges::copy() if it does the same
I see that bandwidth of data being processed in DEBUG mode is much greater with std::ranges::copy() than with eve::algo::copy() in 40 times
I am not asking you to protect your solution and explain to me why it is so. It would do if you just tell me whether it is expectable for the current implementation of eve
PS: There are no questions about -O3 Release mode from me, because with -O3 + LTO there everything works as a reactive plane flies
PSS: Also, be aware, that everything is compiled in -march=native mode that enables everything up to avx512 including

Thank you in advance

**Comment by DenisYaroshevskiy** [comment]
> Why eve doesn't call memmove

We could but then: a) we loose all the tuning abilities. b) memmove is great, just use memmove.
Generally speaking I wouldn't use `eve::algo::copy` for just bytes copying.

>  PSS: Also, be aware, that everything is compiled in -march=native mode that enables everything up to avx512 including

If you use avx512 - I'd recommend to think about frequency scaling https://jfalcou.github.io/eve/freqscale.html - you might get more perf.

**Comment by dpronin** [comment]
@DenisYaroshevskiy I didn't talk about memmove, though :) Is there misundestanding?)

**Comment by DenisYaroshevskiy** [comment]
std::copy is calling memmove under the hood, sorry for misunderstaning.

**Comment by dpronin** [comment]
@DenisYaroshevskiy are you sure? I do not think so, it must not. The ranges must not overlap, but memmove works with possibly overlapping memory. I think std::copy assumes that a source does not intersect a destination.

From https://en.cppreference.com/w/cpp/algorithm/copy

> Copies all elements in the range [first, last) starting from first and proceeding to last.
If d_first is in [first, last), the behavior is undefined. In this case, [std::copy_backward](https://en.cppreference.com/w/cpp/algorithm/copy_backward) may be used instead.

Correct me if I am wrong

**Comment by DenisYaroshevskiy** [comment]
I believe you are, they can overlap one way. And copy_backward are allowed to overlap the other way

In any case: https://github.com/llvm/llvm-project/blob/b0c6fc81fe132f20eed38bd836620dfcb5ac17e9/libcxx/include/__algorithm/copy_move_common.h#L66

**Comment by dpronin** [comment]
@DenisYaroshevskiy thank you, indeed so, again from https://en.cppreference.com/w/cpp/algorithm/copy: 
> In practice, implementations of std::copy avoid multiple assignments and use bulk copy functions such as [std::memmove](https://en.cppreference.com/w/cpp/string/byte/memmove) if the value type is [TriviallyCopyable](https://en.cppreference.com/w/cpp/named_req/TriviallyCopyable) and the iterator types satisfy [LegacyContiguousIterator](https://en.cppreference.com/w/cpp/named_req/ContiguousIterator).

But actually I see a contradiction in the standard because they preserve a well-defined behaviour for trivially copyable POD types  as a _special_ case but warn about everything else to be copied with undefined result. They'd better call memcpy from my point of view to conform their rules and also possibly increase performance. Of course, if they did that they would definitely need to introduce a new algo for copying overlapping objects and memory

Nevertheless, it is quite beside the point of our initial talk
