### ISSUE TITLE
[FEATURE] SIMD-ed Heap

### ISSUE THREAD

**Issue by alantudyk** [jfalcou/eve#1830]
This heap https://github.com/alantudyk/simd_x/tree/master/16-ary_heap is 3x faster than `std::priority_queue`.

(In one specific test on one specific machine. More tests are needed.)

**Comment by DenisYaroshevskiy** [comment]
Cool stuff! I'm interested! Is there like a blog/paper, or just code?

**Comment by alantudyk** [comment]
> Is there like a blog/paper?

Спроси людей в Oracle, есть ли у них "a blog/paper", или же они умеют только тексты заявок на патент составлять: https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2020068611

**Comment by DenisYaroshevskiy** [comment]
I don't believe we can implement a simd heap if they have it patented.

Am I missing something?

**Comment by alantudyk** [comment]
> if they have it patented.

Вот с этим "if" надо разобраться: я плохо понимаю английский и не уверен, что патент пересекается с моим кодом. Кроме того, в США патент не выдан.

**Comment by alantudyk** [comment]
At least a layout is different:

> wherein each node of said plurality of nodes comprises D slots
> ...
> performing a SIMD operation on said root node to generate a first minimum key value

Also, only one particular SSE instraction is mentioned in the patent.
As I said: "надо разобраться".

Денис, у тебя с английским хуже, чем у меня? А разве бывает уровень ниже, чем A0?
