### ISSUE TITLE
Split the largest unit tests

### ISSUE THREAD

**Issue by SadiinsoSnowfall** [jfalcou/eve#1840]
If we only use one thread, around 25% of the build time is spent on 3 tests (in the `compress_copy*` family). If we use 12 threads, the same family of tests are now running for around 60% of the build time, slowing everything else down because of their high memory usage (I recorded a memory usage of up to 95GB while compiling the unit tests with 12 hw threads on my x86 machine, which used a significant volume of swap memory).

<img src="https://github.com/jfalcou/eve/assets/32017313/f4092224-3852-4a80-bd5c-871f8fcbaa68" width=50% height=50%>
<img src="https://github.com/jfalcou/eve/assets/32017313/d025da2a-fafd-4ef6-9f6c-0f6e96451517" width=50% height=50%>

Splitting the longest running tests would speed-up the overall compilation time by reducing the peak memory usage, reducing the need for swapping memory and leaving more headroom for the other concurrent CUs.

**Comment by DenisYaroshevskiy** [comment]
the numbers look enormous - is this avx512? avx512 is especially bad - due to up to 128 elements.

those tests are huge, I already improved/split them a bunch, but if you know how to do better - that's awesome

**Comment by DenisYaroshevskiy** [comment]
Seems like zen3, zen3 should be ok. Is it the same on the nobmi version of the build?

**Comment by jfalcou** [comment]
@SadiinsoSnowfall  we fixed some of those. Can you verify the time spent is better now since the time we merged the fix so we can close this issue.
