### ISSUE TITLE
[BUG] slice_callable is defined incorrectly

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#1943]
https://github.com/jfalcou/eve/blob/89d8ab2092984c3511ecdefeed0ff9c4d96c4fdd/include/eve/detail/function/slice.hpp#L42

Callables should never return auto, otherwise the compiler errors show internals.

**Comment by jfalcou** [comment]
It is an internal callable that is bring wide::slice. Normally it should.give proper error messages anyway. But if you want we can fix it anyway

**Comment by DenisYaroshevskiy** [comment]
I think it's important, especially for enums and such, if we are still doing those
