### ISSUE TITLE
Change template parameter naming style to avoid collisions or confusion

### ISSUE THREAD

**Issue by JPenuchot** [jfalcou/eve#337]
Some template parameters have all-caps names such as `VERSION` or `ISA` (see [`include/eve/detail/spy.hpp:764`](https://github.com/jfalcou/eve/blob/eff59aaf22deef57aa1fcf7561462e3449668883/include/eve/detail/spy.hpp#L764)) that:

- Look like preprocessor variables
- Are already be defined in some cases

I think it's reasonable to change those names to avoid collisions since `VERSION` is a commonly defined variable, my suggestion would be to add a prefix like `EVE_` or `_EVE_` and/or change naming style altogether, as the all caps style might suggest they are preprocessor variables.

**Comment by jfalcou** [comment]
Indeed. Would you mind posting this issue over at github.cim/jfalcou/spy?

**Comment by JPenuchot** [comment]
Ça roule

**Comment by jfalcou** [comment]
Depend son https://github.com/jfalcou/spy/issues/10
