### ISSUE TITLE
[BUG] Confusion about the ABI parameter

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#342]
My understanding of the ABI parameter of the register was that it will be the native ABI of my platform.

So I expected
`eve::wide<char, eve::fixed<16>>` to have `abi` `eve::avx2_` if I compile for `avx2`.

However it is `eve::sse_`.

How am I suppose to use this `abi` parameter then? How to distinguish what platform I am compiling for?

**Comment by jfalcou** [comment]
Sounds like the confusion comes from the rather ad hoc bad naming scheme for ABI type.
I think renaming `sse_` to `x86_128` and have a `x86_256` instead of reusing `avx_` would be better.
