### ISSUE TITLE
[BUG] bitmask codegen for shorts can be improved

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#347]
UPD: This probably should have the common code with conversion from `short` to `char`

This is current code for `sse3` and `sse2` for shorts:

https://github.com/jfalcou/eve/blob/936268b749394872c0cf82e51ae061da1268555a/include/eve/detail/function/simd/x86/bitmask.hpp#L36

It has a hardcoded mask and a shuffle for `sse3` and a scalar implementation for `sse2`.

I think you can do better with `_mm_packs_epi16`.

Smth like:

```
__m128i to_chars = _mm_packs_epi16(p.storage(), _mm_setzero_si128());
return _mm_movemask_epi8(to_chars);
```

Some preliminary testing suggests that it's OK.

I don't know anything horrible about `_mm_packs_epi16 ` - so probably this is an improvement.
It's also available from `sse2`

UPD:

I think for AVX you can implement it like this:

```
    __m128i top = _mm256_extractf128_si256(x, 1);
    __m128i bottom = _mm256_castsi256_si128(x);
    __m128i packed = _mm_packs_epi16(bottom, top);
    return _mm256_movemask_epi8(packed);
```

And recursing is a worth option.

**Comment by jfalcou** [comment]
Sounds good

**Comment by jfalcou** [comment]
Here is some asm for bitmap() on short.

bitmap with pack_epi16:
```
f(eve::logical<eve::wide<short, eve::fixed<8l>, eve::x86_128_> >):
  pxor %xmm1, %xmm1
  packsswb %xmm1, %xmm0
  pmovmskb %xmm0, %eax
  movzbl %al, %eax
  ret
```

SSSE3 bitmap with shufb
```
f(eve::logical<eve::wide<short, eve::fixed<8l>, eve::x86_128_> >):
  pshufb .LC0(%rip), %xmm0
  pmovmskb %xmm0, %eax
  movzbl %al, %eax
  ret
```

Emulated SSE2 bitmap
```
f(eve::logical<eve::wide<short, eve::fixed<8l>, eve::x86_128_> >):
  pextrw $3, %xmm0, %eax
  pextrw $4, %xmm0, %edx
  pextrw $2, %xmm0, %ecx
  testw %ax, %ax
  setne %al
  movzbl %al, %eax
  sall $3, %eax
  testw %dx, %dx
  setne %dl
  movzbl %dl, %edx
  sall $4, %edx
  orl %edx, %eax
  pextrw $0, %xmm0, %edx
  testw %dx, %dx
  cltq
  setne %dl
  movzbl %dl, %edx
  orq %rdx, %rax
  pextrw $5, %xmm0, %edx
  testw %dx, %dx
  setne %dl
  movzbl %dl, %edx
  salq $5, %rdx
  orq %rdx, %rax
  pextrw $6, %xmm0, %edx
  testw %dx, %dx
  setne %dl
  movzbl %dl, %edx
  salq $6, %rdx
  orq %rdx, %rax
  pextrw $7, %xmm0, %edx
  testw %dx, %dx
  setne %dl
  movzbl %dl, %edx
  salq $7, %rdx
  orq %rdx, %rax
  pextrw $1, %xmm0, %edx
  testw %dx, %dx
  setne %dl
  movzbl %dl, %edx
  addl %edx, %edx
  testw %cx, %cx
  setne %cl
  movzbl %cl, %ecx
  sall $2, %ecx
  orl %ecx, %edx
  movslq %edx, %rdx
  orq %rdx, %rax
  ret
```

There is no contest it is an improvement from the old SSE2 case. Now, not sure it's fundamentally better than the shufb version as the pxor induces 1 moe latency cycle. I think we can remove the ugly SSE2 case and replace it with this one. I need to bench the SSSE3 version vs this one.

**Comment by jfalcou** [comment]
The AVX case however is better all the time

**Comment by DenisYaroshevskiy** [comment]
I liked that sse2 version doesn't require a masked.

**Comment by jfalcou** [comment]
OK but, currently, it's less cycle and it sets up an operation on a different port.
Again, this needs benchmarking.

**Comment by DenisYaroshevskiy** [comment]
Up to you
