### ISSUE TITLE
[BUG] Conversion from short to char to on avx2 (and probably avx) generates too much code

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#348]
C++ code:
```
auto test(eve::logical<eve::wide<T>> x) {
  return eve::convert(x, eve::as_<char>{});
}
```

ASM:
```
...
	vextracti128	xmm1, ymm0, 1
	vpinsrw	xmm1, xmm1, word ptr [rsp + 28], 6
	vpinsrw	xmm1, xmm1, word ptr [rsp + 30], 7
	vinserti128	ymm0, ymm0, xmm1, 1
	vpxor	xmm1, xmm1, xmm1
	vpcmpeqw	ymm0, ymm0, ymm1
	vpcmpeqd	ymm1, ymm1, ymm1
	vpxor	ymm0, ymm0, ymm1
	vextracti128	xmm1, ymm0, 1
	vpacksswb	xmm0, xmm0, xmm1
	vpand	xmm0, xmm0, xmmword ptr [rip + .LCPI0_0]
..
```

I believe you can do entire conversion on avx like this:

```
    __m128i top = _mm256_extractf128_si256(x, 1);
    __m128i bottom = _mm256_castsi256_si128(x);
    __m128i packed = _mm_packs_epi16(bottom, top);
```

Haven't  actually tested but a similar technic is used here: https://github.com/jfalcou/eve/issues/347 and I tested that.

**Comment by jfalcou** [comment]
Yes, this is a repeatable pattern of unpack+conversion across all integers and architectures. 
This needs to be in, but I wish we can fix it when the swizzles are there so we can have a generic, architecture agnostic implementation

**Comment by DenisYaroshevskiy** [comment]
How are swizzles going to help?
If you fix it, you can use it in `bitmap` fix.

**Comment by jfalcou** [comment]
Superceded by #534
