### ISSUE TITLE
[BUG] clang test compilation errors.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#358]
Compiling with:

```
eve/build$ cmake -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++" ..
```

clang built from trunk, libc++ as well.

Listing everything, in order to skip things - disable one by one.

1)
```
In file included from tmp-src/exhaustive.core.prev/regular.simd.int8.cpp:31:
/home/dyarosh/space/eve/test/exhaustive/module/core/prev/regular/prev.hpp:27:97: error: 'nan' does not name a template but is followed by template arguments; did you mean 'tan'?
    auto std_prev = tts::vectorize<T>( [](auto e) { return (e ==  eve::minf(eve::as<v_t>())) ?  eve::nan<v_t>() : std::nextafter(e, eve::minf(eve::as<v_t>())); } );
```

As we can see `eve::nan` is a callable.
No template
Did you mean `eve::nan(eve::as<v_t>())` ?

How did gcc allow this?

2)

```
#include <eve/constant/mantissa_bits.hpp>
```
Not a thing.

Did you mean <eve/constant/mantissamask.hpp> ?

3) No idea how to fix bit mantisa tests.

4) libc++ doesn't support `std::beta`

**Comment by jfalcou** [comment]
exhaustive tests are not run automatically cause they're rather long to execute.
The implementation fo the exhaustive ULP histogram in TTS is bad and need to be rewritten.
The feat/faster_test branch is tackling this but basically, for now, the exhaustive test will be deactivated.

**Comment by DenisYaroshevskiy** [comment]
@jfalcou 
this is definitely not only `exhaustive` tests

1)  test/unit/module/special/beta/regular/beta.hpp 

No `std::beta` in libc++

2) include/eve/module/core/function/generic/bit_mantissa.hpp

`Mantissabits_mask` doesn't exist
