### ISSUE TITLE
[BUG] formating is off

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#361]
This is what happens if you run clang-format on `eve`:
https://github.com/jfalcou/eve/pull/360/commits/3b424f2e869efc89ea3eccdd9b0fc3a2f8ae9d14

Seems like you could use:

```
AllowShortIfStatementsOnASingleLine: true
```

This is also weird:

```
 [&w, f ]
```

**Comment by jfalcou** [comment]
Not sure it's a bug. We tried to get decent format options that were OK in C++14/17.
Then when we switched to c++20, clearly clang-format has no idea what to do with "requires" clause, concept and has been bad at dealing with template.

The .clang-format must be rewritten but currently, it just doesn't do what I wish it does in term of style :/

**Comment by DenisYaroshevskiy** [comment]
Apparently the clang format for concepts was implemented: https://reviews.llvm.org/D79773
We should try at some point.

**Comment by jfalcou** [comment]
The branch fix-361/clang-format contains an update clang-format with settings preventing it to mangle some important macro.
Could be cool if you peeps can try it on some files and see how it goes.
