### ISSUE TITLE
[clean-up] Add tests to`Extending Eve(1)`.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#368]
Follow up to #344

The complete implementation is here:
https://gist.github.com/DenisYaroshevskiy/9b2254ebbdb850bda0f8508ea25fa290

But it's not actually compiled.

**Comment by DenisYaroshevskiy** [comment]
@jfalcou is adding `abi_compatible_with` that can be used here

**Comment by jfalcou** [comment]
What is the status on this after recent merges ?

**Comment by DenisYaroshevskiy** [comment]
Not done. I kinda need to do it but didn't yet.

**Comment by jfalcou** [comment]
Referenced in the Master Documenation Issue : https://github.com/jfalcou/eve/issues/1551
