### ISSUE TITLE
[FEATURE] Using precompiled headers in order to achieve faster compilation

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#371]
### What am I compiling?

I am running the following script

```
ninja unit.arch.exe -k 0 -j 16 && ctest -R "^unit.arch\..*\.exe"               && \
ninja unit.api.exe  -k 0 -j 16 && ctest -R "^unit.api\..*\.exe"          -j 16  && \
ninja doc.exe       -k 0 -j 16 && ctest -R "^doc\..*\.exe"               -j 16  && \
ninja unit.simd.exe -k 0 -j 16 && ctest -R "^unit\..*\..*\..*\.simd.exe" -j 16
```

I also tested just all `unit`

```
time ninja -j 16 unit.exe 
```

### Speed up potentials

By default on my machine it takes:

```
Total Test time (real) =   0.29 sec

real    3m16.669s
user    22m19.972s
sys     0m44.698s
```

For building all unittests

```
real    4m31.795s
user    29m39.841s
sys     0m57.345s
```

When I precompiled and reused `test.hpp` it takes:

For selected script:

```
real    2m20.296s
user    16m38.058s
sys     0m33.431s
```

For all tests:

```
real    2m51.614s
user    18m18.923s
sys     0m36.916s
```

### Why is this worth doing.

Hour long CI is a lot. + if we are going to add algorithms, they will add a lot as well.

### Unsolved issues:

It gives me a warning:

```
[902/921] Building CXX object test/unit/module/special/CMakeFiles/unit.special.erfc.regular.simd.exe.dir/__/__/__/__/tmp-src/unit.special.erfc/regular.simd.cpp.o
<built-in>:1:13: warning: ISO C99 requires whitespace after the macro name [-Wc99-extensions]
#define unit.core.gather.aligned.simd.exe 1
```

I don't know what this is.
Is it that `tts` will actually compile differently everywhere?

### Where can we take it next?

Precompiling `eve` would probably save quite a bit but that is going to come at a price of not testing all necessary includes.
Some heavily used standard library.

### Example implementation

https://github.com/jfalcou/eve/pull/372

### Alternative solutions

* Not compile main so many times: unite multiple functions in one binary. Utilise the UNITY_BUILD for target.
* Maybe modules? We luckily have C++20. But modules are not here yet in CMAKE at least and I have not idea what's with compiler support.

**Comment by jfalcou** [comment]
Correct way to do this is to use an INTERFACE apparently

https://github.com/Beyond-Engine/Core/blob/e678869afcd9a37ad4ec96216fa1567c1fea4d34/cmake/compiler.cmake#L59-L76
