### ISSUE TITLE
[BUG] I suspect that `static_alginment` is not the most user friendly

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#380]
This is the code I see for `static_alignment` in eve::wide

```
    static constexpr std::size_t  static_alignment = []()
    {
      if constexpr( std::is_same_v<aggregated_,ABI> )
      {
        return storage_type::value_type::static_alignment;
      }
      else
```

This for example means, that when switching compilation flags your alignment requirements change.
Given how much of SIMD code relies on alignment, things like being able to read the whole register from `previous_aligned_address`, I'd argue that alignment requirement for `aggregated` should also be the `size` same as for non aggregated.

Otherwise I don't see how it's usable.

**Comment by jfalcou** [comment]
The idea was to not have over eager alignment. But I think I see why it may be an issue.

For alignment based function, we need to be careful to use the static alignment tbof a wide type though.

**Comment by DenisYaroshevskiy** [comment]
Right now I rely on alignment `sizeof(T) * static_size()`.
I think it's important that you can always read the register from the aligned address. In which case this `static_alignment` is meaningless.

It's the same idea that you have here:

```
  {
        std::size_t native = alignof(storage_type);
        std::size_t limit  = Size::value * sizeof(Type);
        return std::min(limit, native);
      }
``` 

Just the other way around

**Comment by jfalcou** [comment]
Would having alignment always be based on size make the static_alignment redundant with alignof ? thus making the interface simpler?

**Comment by DenisYaroshevskiy** [comment]
@jfalcou yeah, I believe so

**Comment by jfalcou** [comment]
So in fix/issue-380 branch , we:
  - removed static_alignment
  - Made it so wide alignment is more natural : native alignof for regular ones and aggregate, cardinal*sizeof(T) for emulation and small ones
  - Made aligned_ptr and as_aligned align on SIMD alignment of type by default
  - Added a eve::alignment_v traits simialr to cardinal_v that retrieve the proper alignment of both scalar and sidm types
