### ISSUE TITLE
extend arithmetic_calls

### ISSUE THREAD

**Issue by jtlap** [jfalcou/eve#395]
I want to write an analogous of lerp as cubicrp, but the call needs 5 parameters for the regular case. It will be great to allow arithmetic_call and prhaps the other similar functions to have an arbitrary number of 'arithmetic' parameters to simplify the 
needed code of the mixed scalar/wide parameters

**Comment by jfalcou** [comment]
Fixed in e133b66b7e3ffc1fdbb7011eeaa40826ccd6aad8
