### ISSUE TITLE
[INTERNAL] ASAN builds

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#414]
We already have some tests where asan would be useful - like `load[cond]`
Load unsafe tests will require this as well: https://github.com/jfalcou/eve/issues/290

When we finally get to algorithms, we will also need asan for that.

Suggestion:
1) Check how much just enabling asan hurts the build times
2) If it does create a special target, that has asan enabled. And we will add tests there.

UPD: decided that just SSE2 will suffice

**Comment by jfalcou** [comment]
What do we need to test, just add a "-sanitizer=all" to the options and see?

**Comment by DenisYaroshevskiy** [comment]
| Check how much just enabling asan hurts the build times

This is bad, at least now.
I suspect if we reduce the number of binaries + ideally enable unity builds, we can try again, but at this pont im more then doubles the build times.

x86sse2 - 13 min to 32 min
x86avx - 13 min to 38 min.

Which is a shame, since it finds bugs on top of everything.
+ I suspect, with modules we won't have any other option.

But at this point I'd suggest: let's just create a single test binary for asan tests.
Let's also do at least all pf the types we test in one file.

**Comment by jfalcou** [comment]
Fixed in 6cef970
