### ISSUE TITLE
add a level 'number' to the directory hierarchy just under 'module' level 

### ISSUE THREAD

**Issue by jtlap** [jfalcou/eve#423]
When we are to add complex or automatic derivation to the eve feature it will be necessary to create a full tree
of function reproducing the present 'module' tree.

In fact the present module tree contains all functions treating with 'numbers' numbers being mathematical real numbers (including integers). this module can be called number.
Some day we will have a module complex which will contains similar functions but acting on complex entities: this
will naturally take place in a module/complex directory at the same level as module/number.

Idem for automatic_derivation or double_real or quaternions...

This but be done soon and will also impact the documentation

**Comment by jfalcou** [comment]
Fixed by 1a6aa34cdf84c519dedff8104def0ab33693706b
