### ISSUE TITLE
[FEATURE] top bits abstraction over movemask on x86

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#432]
Working item to create a `top_bits` abstraction.

**Comment by jfalcou** [comment]
IS this the companion issue for #386 PR ?

**Comment by DenisYaroshevskiy** [comment]
For everything but AVX-512 feature is implemented.
For AVX-512 @jfalcou will fix at some point.

**Comment by DenisYaroshevskiy** [comment]
Actually - let's close this one and open a new issue for AVX-512. Why drag issues around.
