### ISSUE TITLE
[BUG] ignore.count method should not be in bytes

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#440]
```
    template<typename T> EVE_FORCEINLINE std::ptrdiff_t offset(eve::as_<T> const&) const
    {
      return count_;
    }
    template<typename T> EVE_FORCEINLINE auto count(eve::as_<T> const&) const
    {
      return sizeof(T) - sizeof(element_type_t<T>) * count_;
    }
 ```
 
 This count method makes no sense, it should return elements.

Also I would like `offset_from_end` or `roffset` or smth.

**Comment by jfalcou** [comment]
It used internally to count how many bytes to `memcpy`. It was organically factored out and I didn't paid attention.
It can be changed to returning # of element and we do the `* sizeof(T)` in the `load[ignore]` code as it's the only place we use this.

`roffset` seems OK to add too
