### ISSUE TITLE
[BUG] Asan failures in tests

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#451]
Couldn't figure out right away so creating this issue.

**doc.core.nth_prime.exe**
Didn't even look
https://gist.github.com/DenisYaroshevskiy/2e51df3f4b499ef4453184f235186290

**unit.api.memory.aligned_ptr.exe**
Complains at the post increment/decrement test. I can't see why.
https://gist.github.com/DenisYaroshevskiy/5af28cd055568b4d7339eb8fab366084

**Comment by jfalcou** [comment]
nth_prime probably try to make a gather with not enough memory.
THe aligned_ptr is more strange.

Or it is a symptom of the lack of load_unsafe

**Comment by DenisYaroshevskiy** [comment]
reported nth_prime separately https://github.com/jfalcou/eve/issues/452 with more details.
I dunno how to fix it properly.

**Comment by DenisYaroshevskiy** [comment]
Fix for `algined_ptr` problem: https://github.com/jfalcou/eve/pull/453
