### ISSUE TITLE
[BUG] eve::maximum

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#479]
eve maximum only has a scalar implementation. 
And a bad one - we need to do batterfly in general and specialise for special instructions.

Also very confusing with eve::max.

And there is no min etc. I think we are missing smth.

I think we need to do a proper job with this.

**Comment by jfalcou** [comment]
Those functions were never implemented further than that, that's all.
We need butterfly shuffle to write it in a single swoop on non-ARM.
ARM butterfly is different.

This will be doable as soon as basic shuffle is merged.
