### ISSUE TITLE
[FEATURE] more CI capacity

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#484]
We don't have enough CI capacity.

We don't have:
* different compilers (especially MSVC)

We are missing many configurations.
We can only afford ASAN on one target.

We talked about the following ideas.
* Add travis CI as well. I believe it ought to have at least one free VM. There is also some plan for 69$ a month. I don't mind paying 69$ a month, but we need to figure out how to use it first.
* Alternatively we can see if we can increase our Circle CI capacity but that might be trickier.
* @jfalcou talked about maybe having an access to some farm somewhere.

**Comment by jfalcou** [comment]
MSVC requires appveyor. I have a basic script somewhere we can reuse. But I guess some work is required on MSVC to compile some c++20 stuff. This I can check locally if neede don my  AVX512 WIndow machine.

Power need an updated Docker. I need an updated doker anyway to have CircleCI display he result of CTest in a better way so this can be done soon.

**Comment by DenisYaroshevskiy** [comment]
@jfalcou - travis ci advertises having windows machines available.
If MSVC is trickier - that can be a different feature.

**Comment by DenisYaroshevskiy** [comment]
@jfalcou - we seem to be ~OK for now. Wanna close this?
