### ISSUE TITLE
[BUG] load for extra wide has a bug with aligned ptrs.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#495]
This is the aggregated load logic.
If I pass a pointer with a bigger alignment that is required for half, it does not work.

`offset + Sub::static_size` is not going to be aligned.

```
//================================================================================================
  // Aggregation
  //================================================================================================
  template<typename T, typename N, typename Pointer>
  EVE_FORCEINLINE auto load(eve::as_<wide<T,N,aggregated_>> const &, Pointer ptr) noexcept
  {
    wide<T,N,aggregated_> that;

    that.storage().apply
    (
      [&]<typename... Sub>(Sub&... v)
      {
        int offset = 0;
        (((v = Sub(ptr + offset), offset += Sub::static_size), ...));
      }
    );

    return that.storage();
  }
```

My personal opinion (we talked about this at some point) is that alignment requirement for any wide should be it's size.
Even for aggregated ones, because:
a) I don't have a use-case for them not to be
b) moving to a different platform will break your alignment requirements
c) it is awkward to work with it. For example: previous aligned address is not OK to load if you rely on alignment, but the alignment is half of your register.

If you really think that this is smth we ought to support - here we need to cast down to the minimum required alignment.

**Comment by jfalcou** [comment]
Currently, the alignment is 

```
    static constexpr auto  static_alignment  = std::min ( sizeof(Type)*Size::value
                                                        , alignof(storage_type)
                                                        );
```

**Comment by DenisYaroshevskiy** [comment]
I would argue it should be: `sizeof(Type)*Size::value`
But in any case we need to cast dow from a bigger alignment

**Comment by jfalcou** [comment]
We should do this change and check what happens

**Comment by DenisYaroshevskiy** [comment]
| We should do this change and check what happens

To clarify: I don't have a very strong opinion on `static_alignment`. But the cast down is for sure just a but.

**Comment by DenisYaroshevskiy** [comment]
Fixing here: https://github.com/jfalcou/eve/pull/499
