### ISSUE TITLE
[FEATURE] unsafe(load[ignore])

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#509]
We can support

```
eve::unsafe(eve::load[eve::ignore_none])(ptr, n);
```

Why this could be useful is:
* you want to tell tsan to go away and part of your register is touched by some other thread.
* you know from some arbitrary reasons that you can only read part of your register.

Not terribly usable I think though but could be implemented and seems consistent with the rest.

It's fairly straightforward but we should do it in a separate pr.

**Comment by jfalcou** [comment]
The rule is that you [] before decorating.

Unsafe( load[ xxx]) (ptr) is the correct syntax

**Comment by DenisYaroshevskiy** [comment]
Ok then. Let's leave this story as an enhancement. Don't want to do it in the same pr.

**Comment by DenisYaroshevskiy** [comment]
https://github.com/jfalcou/eve/pull/571
