### ISSUE TITLE
[FEATURE] 8 chars test on avx512

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#518]
One of the struggles with smaller wides is cleaning up 0 bits on the top.
I believe we miss it on avx512 from time to time.

We need tests for wide<char, eve::fixed<8>>

**Comment by jfalcou** [comment]
Can this be closed since we turned the tests to do all sizes ?

**Comment by DenisYaroshevskiy** [comment]
Sure!
