### ISSUE TITLE
[PROJECT] improve convert to do two steps

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#534]
Converting from let's say uin32 to uint8, for example on  arm, will fall back to scalar.

I think we can in generic case just do convert to next size and then next size.
Needs checking.

**Comment by jfalcou** [comment]
This is what we did in the old Boost.SIMD. This works, we just need to add it back.

**Comment by jfalcou** [comment]
#348 is a duplicate of to this issue.

**Comment by jfalcou** [comment]
Note: this requires native ABI overloads to accept aggregates so we can properly optimizes scenarios like 8 -> 16 bits conversion.

**Comment by jfalcou** [comment]
Fixed in 0189e3c
