### ISSUE TITLE
[BUG] is this code dead?

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#570]
So, this file: https://github.com/jfalcou/eve/blob/67a8fe59c33b6257d4cb3aabb2da759fb7e2cb42/include/eve/module/real/core/function/regular/simd/common/load.hpp#L19

I thought `load(ptr, as_<>)` is not a thing anymore.
Should this be deleted?

**Comment by jfalcou** [comment]
Yes, will do asap
