### ISSUE TITLE
[BUG] Can't build without boost

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#587]
Version of BOOST is wrong:

find_package(Boost 1.65.0 QUIET)
Still tries to find:

```
#include <boost/math/special_functions/jacobi_zeta.hpp>
```

Even if I update the version.

UPD: even when building in docker I hit:

```
../test/doc/core/gegenbauer.cpp:7:10: fatal error: 'boost/math/special_functions/gegenbauer.hpp' file not found
#include <boost/math/special_functions/gegenbauer.hpp>
```

**Comment by jfalcou** [comment]
1/ we need to up Boost version up to 1.7*
2/ this has been fixed, you need to refresh your image
