### ISSUE TITLE
[FEATURE] abs for sse 2 should be done with if/else and not scalar.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#592]
Or other. Can be generally done better.

**Comment by jfalcou** [comment]
SSE2 abs goes through the generic API that uses `if_else`.

**Comment by jfalcou** [comment]
Or do you mean we need SSSE3 support for the integral intrinsics ?

**Comment by DenisYaroshevskiy** [comment]
Generally abs is written in a weird way. We need to look through it carefully.
