### ISSUE TITLE
[BUG] std::bit_width is not yet part of libc++, we shouldn't use it

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#614]
https://godbolt.org/z/sdn7nK

**Comment by jfalcou** [comment]
We need a replacement. As we only need it in constexpr context, we can replicate a simple implementation

**Comment by jfalcou** [comment]
Apparently this mess:

`auto IMAX_BITS(auto m)  { return ((m/(m%255+1) / 255)%255*8 + 7-86/(m%255+12)); }`

computs exactly bit_width(m) + 1.
I propose we call that log_cardinal and put it in eve/detail as an helper.

**Comment by jfalcou** [comment]
Or did we check if clang 12 doesn't just have it ?

**Comment by jfalcou** [comment]
https://godbolt.org/z/oKqx1Y3ra

So closign this now we test with clang-12 ?

**Comment by DenisYaroshevskiy** [comment]
And stdlibc++ on CI?
