### ISSUE TITLE
[FEATURE] eve::replace_ignored should support scalar values

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#686]
We should allow to do things like: `eve::load[eve::ignore_last(1).else(0)](ptr)`.
At the moment it seems to break.

https://godbolt.org/z/nWYr5TjdY

**Comment by jfalcou** [comment]
"funny enough", clang is Ok with it

https://godbolt.org/z/az3jM3GK5

I'll investigate.
