### ISSUE TITLE
[FEATURE] Get mechanism for `traits` in `algo`.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#691]
We need some sort of general purpose mechanism for passing a bag of traits in `algo` to control the algorithm execution.

Things like:
* unrolling
* assume that the start is aligned
* assume that the distance between start and end is divisible by cardinality

We need to support overrides and defaults. We need to support getting traits without pain.

@jfalcou suggested using named parameters which sounds like a good idea.

I'd prefer to have a function:

`eve::algo::traits` to create and pass around traits.

**Comment by jfalcou** [comment]
the function can just be an aggregator of named parameters. Raberu need to gatehr all keyword into a settings object, this is what this raits function can do:

```c++
template<rbr::keyword_parameters... Options>
auto traits(Options const&... opts)
{
  return rbr::settings(opts...);
}
```

example call:

```c++
eve::algo::soem_algo( ptr1, ptr2, alg::traits(  unroll = 4, aligned=true ) );
```

**Comment by DenisYaroshevskiy** [comment]
This looks awesome.
Can we do it as a first parameter same as std policies?
The last is usually the lambda

```
eve::algo::any_of( algo::traits( unroll = 1), f, l, [] (auto x){
   return 3 < x && x < 5;
});
