### ISSUE TITLE
[FEATURE] Generic tests for find like algorithms

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#698]
Testing algorithms is a tricky exercise.

a) should cover different iterator types
b) different traits
c) exercise different parts in the iteration pattern
d) test corner cases around page ends

And compile + run in a reasonable time.

Ideally at least for algorithms like `find` and `all/any/none` we should be able to do them in a generic way.

Obviously this is a process to get there but there should be some framework around doing this.

**Comment by jfalcou** [comment]
Radical idea: get inspiration from listed tests for std algorithm?

**Comment by DenisYaroshevskiy** [comment]
Not enough by a long shot. We care about left and right side of the range being in different addresses.
We care about aligned/unaligned. Different unrolling requiremenets and different iterator types.

On the other hand the standard library is not allowed to rely on standard library in its tests.

**Comment by DenisYaroshevskiy** [comment]
I think what we have is reasonable
