### ISSUE TITLE
[FEATURE] change_cardinal/converting_iterator

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#718]
`I::change_cardinal(eve::fixed)`

For all of our iterators implement a method that returns an iterator with a given cardinal.
For `aligned_ptr_iterator` should require that the new cardinal is <= the cardinal of the iterator.
For `zip_iterator` should check that all cardinals can be changed.

`converting_iterator<I, T>`

Given an iterator on `load` calls convert from an underlying type to its type.
On `store` the other way around.

**Comment by jfalcou** [comment]
wide and logical have something like that as a traits called rescale
Could be cool if we keep the name

**Comment by DenisYaroshevskiy** [comment]
> wide and logical have something like that as a traits called rescale
Could be cool if we keep the name

Didn't happen. May change later
