### ISSUE TITLE
Werror seems to be missing on ci

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#740]
We have an unused variable.

https://github.com/jfalcou/eve/blob/915d4bf26b7da374532c656db83d334aa79b06e8/include/eve/detail/function/simd/x86/friends.hpp#L167

Which means CI doesn't have warnings enabled well enough :(

**Comment by jfalcou** [comment]
Which configuration cause locally, the toolchain do add the options.

**Comment by jfalcou** [comment]
We checked and options are indeed passed
