### ISSUE TITLE
[BUG] Dead files?

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#742]
Seems like the following files are never used, judging by automatic system not finding them:

include/eve/module/real/core/function/numeric/simd/arm/neon/fma.hpp
include/eve/module/real/core/function/numeric/simd/arm/neon/fms.hpp
include/eve/module/real/core/function/numeric/simd/arm/neon/fnma.hpp
include/eve/module/real/core/function/numeric/simd/arm/neon/fnms.hpp
include/eve/module/real/core/function/pedantic/simd/arm/neon/fma.hpp
include/eve/module/real/core/function/pedantic/simd/arm/neon/fms.hpp
include/eve/module/real/core/function/pedantic/simd/arm/neon/fnms.hpp
include/eve/module/real/core/function/regular/simd/arm/neon/minus.hpp

I think I have boost enabled, so it's kinda weird

**Comment by jfalcou** [comment]
the numeric and pedantic fma variant should be included by include/eve/function/numeric/fma.hpp and friends

include/eve/module/real/core/function/regular/simd/arm/neon/minus.hpp code should be moved to arm/friends.hpp under the name self_negate

**Comment by jfalcou** [comment]
@jtlap must confirm if the ARM fm* are in fact needed or not

**Comment by jfalcou** [comment]
Apparently the NEON fm* in numeric/pedantic are maybe actually useless too
