### ISSUE TITLE
[BUG] extract.hpp does not include detail files

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#743]
I'm not sure it should, but for example: include/eve/module/real/core/function/regular/simd/arm/neon/extract.hpp
is not included anywhere

Intel `include/eve/module/real/core/function/regular/simd/x86/extract.hpp`
seems to be missing as well

**Comment by jfalcou** [comment]
those are old code, the whole extract file set should disappear

**Comment by DenisYaroshevskiy** [comment]
Removed
