### ISSUE TITLE
[BUG] `is_not_greater` and friends - why are this a thing?

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#746]
I can see some intrincics code in:
include/eve/module/real/core/function/regular/simd/x86/is_not_greater.hpp
include/eve/module/real/core/function/regular/simd/x86/is_not_less_equal.hpp
include/eve/module/real/core/function/regular/simd/x86/is_not_less.hpp

But it should just forward to operator <=, that's 100% the same thing. Why does this code exist?

**UPD: ** is this about Nan?

**Comment by jfalcou** [comment]
It is about NaN
