### ISSUE TITLE
[BUG] what's the difference between `floor` and `trunc`?

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#748]
Both functions do the same thing on x86 as far as I can see

**Comment by jtlap** [comment]
did you get my mail answer ?

**Comment by DenisYaroshevskiy** [comment]
> did you get my mail answer ?

I don't believe I did.

**Comment by jtlap** [comment]
so, trunc is a truncature it removes the fractional part and is equal to floor if x >=0
floor is the greatest integral less or equal to x 
trunc(-1.5) == -1 floor((-1.5)==-2
ceil must be obvious now?!

**Comment by DenisYaroshevskiy** [comment]
Ok - so trunc is round to zero  and floor is round to lower, gotcha.

Then this is wrong, right? https://github.com/jfalcou/eve/blob/d667de375b05ed9a8b0bbb2c79f8dd6f86f3d242/include/eve/module/real/core/function/regular/simd/x86/floor.hpp#L26

And it should be '_MM_FROUND_TO_NEG_INF'?

**Comment by jtlap** [comment]
you're right
