### ISSUE TITLE
[BUG] Is `negate` the right name for the function?

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#751]
I'd assume that `negate` is going to invert the sign. But it makes all positive numbers zeroes.

https://github.com/jfalcou/eve/blob/d667de375b05ed9a8b0bbb2c79f8dd6f86f3d242/include/eve/module/real/core/function/regular/generic/negate.hpp#L37
https://github.com/jfalcou/eve/blob/d667de375b05ed9a8b0bbb2c79f8dd6f86f3d242/include/eve/module/real/core/function/regular/simd/x86/negate.hpp#L22

Should it be called smth else?

**Comment by jtlap** [comment]
it's not true negate is x*sign(y) and sign(y) is zero iff y is zero
We have signnz and negatenz for wich sign(0) is one (and signn(-0.0) -1 in pedantic cases)

**Comment by DenisYaroshevskiy** [comment]
@jtlap  - yeah, you are correct.
Still - is this the best name?

**Comment by DenisYaroshevskiy** [comment]
Feel free to close this.
