### ISSUE TITLE
[FEATURE] xop testing?

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#752]
We have some `supports_xop` code.
I am not too sure it's actually valuable enough to keep.
But if it is - it needs to be on CI.

**Comment by jfalcou** [comment]
XOP is AMD AVX2 sort of. We need a AMD machine for that and I don't think there is a AMD equivalent to SDE :/
Maybe they could be phased out ?

**Comment by jfalcou** [comment]
After snooping around, looks like XOP is no more available on AMD machine since a  bunch of time.
Should we just drop it ?

**Comment by DenisYaroshevskiy** [comment]
And delete the code! Yes plz

**Comment by jtlap** [comment]
and suppress the ref to XOP in the doc

**Comment by jfalcou** [comment]
Done
