### ISSUE TITLE
[FEATURE] rhsr/ rhsl x86 impl

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#753]
I'm not too sure what `rshl/rhsr` suppose to do.

Current implementations are just `shift` on `xop`.

We have a bunch of shifts on regular x86, we can maybe do these better.

**Comment by jtlap** [comment]
rshl and rshr are shifts that go respectively right and left if the second param is >=0 and reversed if not

**Comment by DenisYaroshevskiy** [comment]
O_o, I see. then the generic implementation of mixing two shifts is probably the best we can do.
