### ISSUE TITLE
[FEATURE] Rudimentary `std::ranges` support

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#762]
libcxx does not have ranges support yet.
Also clang doesn't compile libstdc++ ranges.

We cannot properly depend on it - we need some minimal proper hack in place.

**Comment by jfalcou** [comment]
Isn't it fixed by latest libcxx commit (#829) ?

**Comment by DenisYaroshevskiy** [comment]
Yep
