### ISSUE TITLE
[FEATURE] first_false

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#767]
I know we kinda planned to assume `not` can be optimised.
But I am a bit worried.

And `std::find_if_not` is a thing.

So I'm going to implement first_false

**Comment by DenisYaroshevskiy** [comment]
After thinking about it - I'm not sure we should do it now.
I prototyped a bit, but it's not clear how all of the interfaces should look.

Sometime back we made a decision: `!logical` is optimised well enough.
I'd need to check that assumption again and then:
if it's true - keep using `!logical`
if it's not - introduce `not<logical>`

**Comment by jfalcou** [comment]
Dropping for now
