### ISSUE TITLE
[FEATURE] conditional.mask should be tested for sub-cardinal size and fixed accordingly

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#816]
I think this makes sense.

The code is duplicated between different conditionals.
There is limited testing.

A proper function that just operates on the concept is needed.

As part of this please fix the unseen part of the mask - it should always be false.
(And fix a test in compress store).

**Comment by jfalcou** [comment]
This can just be an overload of bit_mask that do a similar tasks for regular wide

**Comment by DenisYaroshevskiy** [comment]
Wait, bit_mask returns a bit for each element.
conditional.mask - returns a logical.

We have to_logical for top_bits, that is similar:
https://github.com/jfalcou/eve/blob/ac503f6a0378e2bc9f01d634ed13f04865a1dd92/include/eve/detail/top_bits.hpp#L327

This can be a `to_logical`, the `eve` one.

**Comment by jfalcou** [comment]
We discussed the fact `cond.mask( as<T>() )` is enough as interface but that the non used parts of it must be cleaned up.
