### ISSUE TITLE
count_true name

### ISSUE THREAD

**Issue by jtlap** [jfalcou/eve#848]
I think that count_true is not a good name. 
It is too similar to countl_xxx and countr_xxx families with a too different semantic.

the countl_xxx family has names from std:: scalar equivalents. Perhaps it is these names
that are to be changed ?

**Comment by DenisYaroshevskiy** [comment]
It follows first_true name.
I would also like count_false, last_true, nth_true, first_false, last_false, nth_false at some point.

Or smth like that.

What names are you thinking?

**Comment by jfalcou** [comment]
`count_true` is ok, that's the other `countl/r` things we copied from std that should change maybe

**Comment by jfalcou** [comment]
Closed as @jtlap agrees it's a non issue
