### ISSUE TITLE
[FEATURE] compress store for zip

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#868]
* allow any logical to be used with any wide.
* use that to implement compress store for zip.

**Comment by jfalcou** [comment]
isn't first part the same as #594 ?

**Comment by DenisYaroshevskiy** [comment]
@jfalcou I meant in compress_store

**Comment by DenisYaroshevskiy** [comment]
Detailed explanation of what needs to be done for the first part.

### Goal

At this point the interface to compress store is:

```
  template<relative_conditional_expr C, real_scalar_value T, typename N, simd_compatible_ptr<wide<T, N>> Ptr>
  EVE_FORCEINLINE
  T* compress_store_(EVE_SUPPORTS(cpu_),
                    C c,
                    unsafe_type,  // can be safe_type too
                    wide<T, N> v,
                    logical<wide<T, N>> mask,
                    Ptr ptr) noexcept
```

And it's called as:

```
out = eve::unsafe(eve::compress_store[c])(x, m, ap_t{actual.begin()});
```

However, what to do with `bundle`?  If we just going to call the scalar version, it will be extra inefficient, since the `mask` needs to be converted for each type and all of the computations, that will be identical for all fields, have to be performed.

So - what should change? We need to accept any mask type with the same cardinal. ( `logical<wide<U, N>> ` instead of `logical<wide<T, N>>`

```
  template<relative_conditional_expr C, real_scalar_value T, real_scalar_value U, typename N, simd_compatible_ptr<wide<T, N>> Ptr>
  EVE_FORCEINLINE
  T* compress_store_(EVE_SUPPORTS(cpu_),
                    C c,
                    unsafe_type,  // can be safe_type too
                    wide<T, N> v,
                    logical<wide<U, N>> mask, 
                    Ptr ptr) noexcept
```

And then, hopefully, the compiler will see through the duplicated computations and only do them once.

### How to get there

`generic/compress_store.hpp`,  `common/compress_store_impl.hpp`
should probably change by just accepting the mask of a different type, everything else should work.
A few special case tests with different mask types will be enough.

https://github.com/jfalcou/eve/blob/c135a786dc9028d357ba6dcdd2e1f5cb8b7e4d87/include/eve/module/real/core/function/regular/generic/compress_store.hpp#L16
https://github.com/jfalcou/eve/blob/c135a786dc9028d357ba6dcdd2e1f5cb8b7e4d87/include/eve/detail/function/simd/common/compress_store_impl.hpp#L1
 
The more tricky part is x86 implementation.

There are 3 things done with logicals here:
* if_else - should just work
* computing a mask index/ popcount.

The popcount sometimes is stored in the pattern table (for example, before sse4.smth it's not an instruction.
The logic for logical processing has to be extracted and tested separately, so that we don't get an explosion of `wide`/`logical` combinations in testing. However, it seems tricky.

**Comment by DenisYaroshevskiy** [comment]
Done
