### ISSUE TITLE
[FEATURE] load/store scalar relaxed iterator interface.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#907]
Scalar interface is important, however the current operator* is most definitely not the answer.

@jfalcou mentioned that there is some eve scalar interface, we can try that.

I also think that for `map` it's OK to do `broadcast` - apply operation and then `get` the element (if you use scalar operation on `map` it's on you. Or we can give a hook.

Anyways, map is not a thing so far, we want to agree on scalar interface and implement it in iterators.

**Comment by DenisYaroshevskiy** [comment]
Decision:

```
eve::read(it) -> scalar
eve::write(it, value_type<it>)
```

**Comment by jfalcou** [comment]
Does 6fcdbc6 fixes this or do we need to wait for all iterator to implement them ?

**Comment by DenisYaroshevskiy** [comment]
I think, let's wait for that? And adjust the concepts & such.

**Comment by DenisYaroshevskiy** [comment]
https://github.com/jfalcou/eve/pull/920
