### ISSUE TITLE
[FEATURE] constants for product types

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#932]
We should think about how these work

**Comment by jfalcou** [comment]
while writing the double double class, @jtlap had an issue with this.
In the bowels of the optimized `if_else`, we were constructing constant over product type by splatting the value in all fileds.
However, structs like complex or double double, we have a tag_dispacth for that.

By changing the if else code to call the constant generator directly on the product type, the error is fixed. Now, it means that the constant are generated as { value 0 0  ... }.

We can say that this is what we want by default and we don't need to wite anything OR I can add a special case in the constants to go back to the map based behavior.

What you think ?

**Comment by DenisYaroshevskiy** [comment]
Like : complex {1.0} should produce complex {1.0, 0.0} ? 

filling  with one value different fields is obviously wrong

I'd expect if_else(cond, like<complex>, like<complex>) and nothing else

**Comment by jfalcou** [comment]
Complex does have a correct if_else but it reuses the common one for optimisation, that's where the error was.
See https://github.com/jfalcou/eve/pull/1529 for a fix

We just need to decide what we do we random, non-specialized for constant product type.

**Comment by jfalcou** [comment]
We discussed and decided to prevent non specific tuple like type to not support constant generation. To be done in a subsequent PR.
