### ISSUE TITLE
[BUG] type selection for `inclusive_scan`/`reduce`

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#938]
Our behaviour on overflows does not well match the standard.
Generally, we will overflow in less cases.

We should do what the standard does unless we have a reason to do otherwise.

The reason this happens is because at the moment we only have `common_type` tag but we can't force a type.
Or maybe we can but I didn't try.

**Comment by jfalcou** [comment]
I we overflow less, isn't it a better behavior and should stay as it is ?

**Comment by DenisYaroshevskiy** [comment]
https://github.com/jfalcou/eve/pull/977
