### ISSUE TITLE
[FEATURE] switch based compress store

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#947]
Try using switch based compress store, it's not that many options and might be good for up to 4 elements.
If this is good enough, I believe we can also try mask shinking on avx2, since the last time I stopped at necessity to generate 4 bytes of shuffle from an index.

switch based shuffle can also be our saviour on sse2

**Comment by jfalcou** [comment]
didn't we have it implemented ? Should this be closed ?

**Comment by DenisYaroshevskiy** [comment]
Yep!
