### ISSUE TITLE
[FEATURE] check that conversion from 8 64 bit logicals to 8 32 bit logicals is properly optimized on x86.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#967]
Don't want to spend time on it right now. Is very doable if not.

**Comment by jfalcou** [comment]
Related to #534

**Comment by jfalcou** [comment]
Fix in [0189e3c](https://github.com/jfalcou/eve/commit/0189e3c3e575295ea0fb75263a1e576279e1234f)
